/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import configuracion.Barrio_consulta;
import configuracion.Calles_consulta;
import configuracion.Caracter_Consulta;
import configuracion.Cargo_consulta;
import configuracion.Cursado_consulta;
import configuracion.Gremio_consulta;
import configuracion.Localidad_consulta;
import configuracion.Nacionalidad_consulta;
import configuracion.Periodo_consulta;
import configuracion.Plan_consulta;
import configuracion.Sexo_consulta;
import configuracion.TipoDoc_consulta;
import configuracion.Titulo_consulta;
import configuracion.Trabajo_consulta;
import curso.CrearCurso;
import curso.EliminarCurso;
import curso.Horario;
import curso.ModificarCurso;
import interfazAlumno.AsignarCurso;
import interfazAlumno.AsignarCurso1;
import interfazAlumno.DarBajaCurso1;
import interfazEmpleado.AsignarCursoAcargo1;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import licencia.*;
import listado.*;
import usuario.*;

/**
 *
 * @author araa
 */
public class Principal extends javax.swing.JFrame {

    public static int alumnoMenu=0;
    public static int empleadoMenu=0;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        menuBar.setVisible(false);
        Login log=new Login();
        principal.add(log);
        log.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        exitMenuItem10 = new javax.swing.JMenuItem();
        exitMenuItem8 = new javax.swing.JMenuItem();
        exitMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        exitMenuItem2 = new javax.swing.JMenuItem();
        exitMenuItem3 = new javax.swing.JMenuItem();
        exitMenuItem4 = new javax.swing.JMenuItem();
        exitMenuItem6 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        exitMenuItem1 = new javax.swing.JMenuItem();
        exitMenuItem7 = new javax.swing.JMenuItem();
        exitMenuItem9 = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        registrarAlumno = new javax.swing.JMenuItem();
        modificarAlumno = new javax.swing.JMenuItem();
        asignarCurso = new javax.swing.JMenuItem();
        darBaja = new javax.swing.JMenuItem();
        efectuarPago = new javax.swing.JMenuItem();
        consultarAlumno = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        registrar = new javax.swing.JMenuItem();
        modificar = new javax.swing.JMenuItem();
        asignarCursoEmpleado = new javax.swing.JMenuItem();
        darBajaEmpleado = new javax.swing.JMenuItem();
        consultarEmpleado = new javax.swing.JMenuItem();
        helpMenu1 = new javax.swing.JMenu();
        contentMenuItem1 = new javax.swing.JMenuItem();
        aboutMenuItem1 = new javax.swing.JMenuItem();
        aboutMenuItem9 = new javax.swing.JMenuItem();
        aboutMenuItem10 = new javax.swing.JMenuItem();
        aboutMenuItem11 = new javax.swing.JMenuItem();
        helpMenu2 = new javax.swing.JMenu();
        contentMenuItem2 = new javax.swing.JMenuItem();
        aboutMenuItem2 = new javax.swing.JMenuItem();
        aboutMenuItem12 = new javax.swing.JMenuItem();
        aboutMenuItem13 = new javax.swing.JMenuItem();
        helpMenu3 = new javax.swing.JMenu();
        contentMenuItem3 = new javax.swing.JMenuItem();
        aboutMenuItem3 = new javax.swing.JMenuItem();
        aboutMenuItem14 = new javax.swing.JMenuItem();
        aboutMenuItem15 = new javax.swing.JMenuItem();
        helpMenu4 = new javax.swing.JMenu();
        contentMenuItem4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        aboutMenuItem16 = new javax.swing.JMenuItem();
        helpMenu5 = new javax.swing.JMenu();
        aboutMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jMenu2.setText("Configuracion");

        jMenu3.setText("Lugar");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Calle");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Barrio");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Localidad");
        saveAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Nacionalidad");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(exitMenuItem);

        jMenu2.add(jMenu3);

        jMenu4.setText("Alumno");

        exitMenuItem10.setMnemonic('x');
        exitMenuItem10.setText("Trabajo");
        exitMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(exitMenuItem10);

        exitMenuItem8.setMnemonic('x');
        exitMenuItem8.setText("Lugar cursado");
        exitMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(exitMenuItem8);

        exitMenuItem5.setMnemonic('x');
        exitMenuItem5.setText("Plan");
        exitMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(exitMenuItem5);

        jMenu2.add(jMenu4);

        jMenu5.setText("Empleado");

        exitMenuItem2.setMnemonic('x');
        exitMenuItem2.setText("Cargo");
        exitMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(exitMenuItem2);

        exitMenuItem3.setMnemonic('x');
        exitMenuItem3.setText("Titulo");
        exitMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(exitMenuItem3);

        exitMenuItem4.setMnemonic('x');
        exitMenuItem4.setText("Caracter");
        exitMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(exitMenuItem4);

        exitMenuItem6.setMnemonic('x');
        exitMenuItem6.setText("Gremio");
        exitMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(exitMenuItem6);

        jMenu2.add(jMenu5);

        jMenu6.setText("General");

        exitMenuItem1.setMnemonic('x');
        exitMenuItem1.setText("Tipo documento");
        exitMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(exitMenuItem1);

        exitMenuItem7.setMnemonic('x');
        exitMenuItem7.setText("Sexo");
        exitMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItem7ActionPerformed(evt);
            }
        });
        jMenu6.add(exitMenuItem7);

        exitMenuItem9.setMnemonic('x');
        exitMenuItem9.setText("Periodo");
        exitMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItem9ActionPerformed(evt);
            }
        });
        jMenu6.add(exitMenuItem9);

        jMenu2.add(jMenu6);

        menuBar.add(jMenu2);

        editMenu.setMnemonic('e');
        editMenu.setText("Alumnos");

        registrarAlumno.setMnemonic('t');
        registrarAlumno.setText("Registrar");
        registrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarAlumnoActionPerformed(evt);
            }
        });
        editMenu.add(registrarAlumno);

        modificarAlumno.setMnemonic('y');
        modificarAlumno.setText("Modificar datos");
        modificarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarAlumnoActionPerformed(evt);
            }
        });
        editMenu.add(modificarAlumno);

        asignarCurso.setMnemonic('p');
        asignarCurso.setText("Asignar cursos");
        asignarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignarCursoActionPerformed(evt);
            }
        });
        editMenu.add(asignarCurso);

        darBaja.setMnemonic('d');
        darBaja.setText("Dar baja de cursos");
        darBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darBajaActionPerformed(evt);
            }
        });
        editMenu.add(darBaja);

        efectuarPago.setMnemonic('d');
        efectuarPago.setText("Efectuar pago");
        efectuarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efectuarPagoActionPerformed(evt);
            }
        });
        editMenu.add(efectuarPago);

        consultarAlumno.setMnemonic('d');
        consultarAlumno.setText("Consulta de datos");
        consultarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarAlumnoActionPerformed(evt);
            }
        });
        editMenu.add(consultarAlumno);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Empleados");

        registrar.setMnemonic('c');
        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        helpMenu.add(registrar);

        modificar.setMnemonic('a');
        modificar.setText("Modificar datos");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        helpMenu.add(modificar);

        asignarCursoEmpleado.setMnemonic('a');
        asignarCursoEmpleado.setText("Asignar cursos");
        asignarCursoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignarCursoEmpleadoActionPerformed(evt);
            }
        });
        helpMenu.add(asignarCursoEmpleado);

        darBajaEmpleado.setMnemonic('a');
        darBajaEmpleado.setText("Dar de baja a cursos");
        darBajaEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darBajaEmpleadoActionPerformed(evt);
            }
        });
        helpMenu.add(darBajaEmpleado);

        consultarEmpleado.setMnemonic('a');
        consultarEmpleado.setText("Consulta de datos");
        consultarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarEmpleadoActionPerformed(evt);
            }
        });
        helpMenu.add(consultarEmpleado);

        menuBar.add(helpMenu);

        helpMenu1.setMnemonic('h');
        helpMenu1.setText("Listados");

        contentMenuItem1.setMnemonic('c');
        contentMenuItem1.setText("Por curso");
        contentMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItem1ActionPerformed(evt);
            }
        });
        helpMenu1.add(contentMenuItem1);

        aboutMenuItem1.setMnemonic('a');
        aboutMenuItem1.setText("Por ciclo lectivo");
        aboutMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItem1ActionPerformed(evt);
            }
        });
        helpMenu1.add(aboutMenuItem1);

        aboutMenuItem9.setMnemonic('a');
        aboutMenuItem9.setText("Deudores");
        aboutMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItem9ActionPerformed(evt);
            }
        });
        helpMenu1.add(aboutMenuItem9);

        aboutMenuItem10.setMnemonic('a');
        aboutMenuItem10.setText("Egresados");
        aboutMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItem10ActionPerformed(evt);
            }
        });
        helpMenu1.add(aboutMenuItem10);

        aboutMenuItem11.setMnemonic('a');
        aboutMenuItem11.setText("Deserción");
        aboutMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItem11ActionPerformed(evt);
            }
        });
        helpMenu1.add(aboutMenuItem11);

        menuBar.add(helpMenu1);

        helpMenu2.setMnemonic('h');
        helpMenu2.setText("Licencias");

        contentMenuItem2.setMnemonic('c');
        contentMenuItem2.setText("Crear artículos");
        contentMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItem2ActionPerformed(evt);
            }
        });
        helpMenu2.add(contentMenuItem2);

        aboutMenuItem2.setMnemonic('a');
        aboutMenuItem2.setText("Asignar licencias");
        aboutMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItem2ActionPerformed(evt);
            }
        });
        helpMenu2.add(aboutMenuItem2);

        aboutMenuItem12.setMnemonic('a');
        aboutMenuItem12.setText("Modificar licencias");
        aboutMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItem12ActionPerformed(evt);
            }
        });
        helpMenu2.add(aboutMenuItem12);

        aboutMenuItem13.setMnemonic('a');
        aboutMenuItem13.setText("Consulta");
        aboutMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItem13ActionPerformed(evt);
            }
        });
        helpMenu2.add(aboutMenuItem13);

        menuBar.add(helpMenu2);

        helpMenu3.setMnemonic('h');
        helpMenu3.setText("Cursos");

        contentMenuItem3.setMnemonic('c');
        contentMenuItem3.setText("Crear cursos");
        contentMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItem3ActionPerformed(evt);
            }
        });
        helpMenu3.add(contentMenuItem3);

        aboutMenuItem3.setMnemonic('a');
        aboutMenuItem3.setText("Modificar cursos");
        aboutMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItem3ActionPerformed(evt);
            }
        });
        helpMenu3.add(aboutMenuItem3);

        aboutMenuItem14.setMnemonic('a');
        aboutMenuItem14.setText("Crear horarios");
        aboutMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItem14ActionPerformed(evt);
            }
        });
        helpMenu3.add(aboutMenuItem14);

        aboutMenuItem15.setMnemonic('a');
        aboutMenuItem15.setText("Eliminar cursos");
        aboutMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItem15ActionPerformed(evt);
            }
        });
        helpMenu3.add(aboutMenuItem15);

        menuBar.add(helpMenu3);

        helpMenu4.setMnemonic('h');
        helpMenu4.setText("Usuarios");

        contentMenuItem4.setMnemonic('c');
        contentMenuItem4.setText("Crear usuarios");
        contentMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItem4ActionPerformed(evt);
            }
        });
        helpMenu4.add(contentMenuItem4);

        jMenu1.setText("Modificar usuarios");

        jMenuItem1.setText("Cambiar nombre de usuario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Cambiar contraseña");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        helpMenu4.add(jMenu1);

        aboutMenuItem16.setMnemonic('a');
        aboutMenuItem16.setText("Eliminar usuarios");
        aboutMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItem16ActionPerformed(evt);
            }
        });
        helpMenu4.add(aboutMenuItem16);

        menuBar.add(helpMenu4);

        helpMenu5.setMnemonic('h');
        helpMenu5.setText("Salir");

        aboutMenuItem5.setMnemonic('a');
        aboutMenuItem5.setText("Salir");
        aboutMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItem5ActionPerformed(evt);
            }
        });
        helpMenu5.add(aboutMenuItem5);

        menuBar.add(helpMenu5);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, 999, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        try {
            Nacionalidad_consulta nacion=new Nacionalidad_consulta();
            Principal.principal.add(nacion);
            nacion.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void exitMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItem1ActionPerformed
        try {
            // TODO add your handling code here:
            TipoDoc_consulta tipo=new TipoDoc_consulta();
            Principal.principal.add(tipo);
            tipo.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_exitMenuItem1ActionPerformed

    private void exitMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItem2ActionPerformed
        try {
            // TODO add your handling code here:
            Cargo_consulta cargo=new Cargo_consulta();
            Principal.principal.add(cargo);
            cargo.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_exitMenuItem2ActionPerformed

    private void exitMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItem3ActionPerformed
        try {
            // TODO add your handling code here:
            Titulo_consulta titulo=new Titulo_consulta();
            Principal.principal.add(titulo);
            titulo.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_exitMenuItem3ActionPerformed

    private void exitMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItem4ActionPerformed
        // TODO add your handling code here:
        Caracter_Consulta caracter=new Caracter_Consulta();
        Principal.principal.add(caracter);
        caracter.setVisible(true);
    }//GEN-LAST:event_exitMenuItem4ActionPerformed

    private void exitMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItem5ActionPerformed
        try {
            // TODO add your handling code here:

            Plan_consulta plan=new Plan_consulta();
            Principal.principal.add(plan);
            plan.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_exitMenuItem5ActionPerformed

    private void exitMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItem6ActionPerformed
        try {
            // TODO add your handling code here:
            Gremio_consulta gremio=new Gremio_consulta();
            Principal.principal.add(gremio);
            gremio.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_exitMenuItem6ActionPerformed

    private void exitMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItem7ActionPerformed
        try {
            // TODO add your handling code here:
            Sexo_consulta sx=new Sexo_consulta();
            Principal.principal.add(sx);
            sx.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_exitMenuItem7ActionPerformed

    private void exitMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItem8ActionPerformed
        try {
            // TODO add your handling code here:
            Cursado_consulta lugar=new Cursado_consulta();
            Principal.principal.add(lugar);
            lugar.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_exitMenuItem8ActionPerformed

    private void exitMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItem9ActionPerformed
        try {
            // TODO add your handling code here:
            Periodo_consulta periodo=new Periodo_consulta();
            Principal.principal.add(periodo);
            periodo.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_exitMenuItem9ActionPerformed

    private void exitMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItem10ActionPerformed
        try {
            // TODO add your handling code here:
            Trabajo_consulta trabajo=new Trabajo_consulta();
            Principal.principal.add(trabajo);
            trabajo.setVisible(true);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_exitMenuItem10ActionPerformed

    private void consultarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarAlumnoActionPerformed
        // TODO add your handling code here:
        alumnoMenu=6;
        
        FormDni.alumnoEmpleadoUser=1;
        panelDni();
    }//GEN-LAST:event_consultarAlumnoActionPerformed

    private void contentMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItem1ActionPerformed
        // TODO add your handling code here:
        ListadoPorCurso cp=new ListadoPorCurso();
        Principal.principal.add(cp);
        cp.setVisible(true);
    }//GEN-LAST:event_contentMenuItem1ActionPerformed

    private void aboutMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItem10ActionPerformed
        // TODO add your handling code here:
        //        EgresadoDesercion ed=new EgresadoDesercion(3);
        EgresadoDesercion ed=new EgresadoDesercion();
        Principal.principal.add(ed);
        ed.setVisible(true);
    }//GEN-LAST:event_aboutMenuItem10ActionPerformed

    private void aboutMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItem3ActionPerformed
        // TODO add your handling code here:
        ModificarCurso curso= new ModificarCurso();
        Principal.principal.add(curso);
        curso.setVisible(true);
    }//GEN-LAST:event_aboutMenuItem3ActionPerformed

    private void registrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarAlumnoActionPerformed
        // TODO add your handling code here:
        FormDni.alumnoEmpleadoUser=1;
        alumnoMenu=1;
        panelDni();
    }//GEN-LAST:event_registrarAlumnoActionPerformed

    private void modificarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarAlumnoActionPerformed
        // TODO add your handling code here:       
        alumnoMenu=2;
        FormDni.alumnoEmpleadoUser=1;
        
        panelDni();
    }//GEN-LAST:event_modificarAlumnoActionPerformed

    private void asignarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignarCursoActionPerformed
        // TODO add your handling code here:
        alumnoMenu=3;
        FormDni.alumnoEmpleadoUser=1;
        AsignarCurso1 asignar=new AsignarCurso1();
        Principal.principal.add(asignar);
        asignar.setVisible(true);
    }//GEN-LAST:event_asignarCursoActionPerformed

    private void darBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darBajaActionPerformed
        // TODO add your handling code here:7
        alumnoMenu=4;
        FormDni.alumnoEmpleadoUser=1;
        DarBajaCurso1 baja=new DarBajaCurso1();
        Principal.principal.add(baja);
        baja.setVisible(true);
    }//GEN-LAST:event_darBajaActionPerformed

    private void efectuarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efectuarPagoActionPerformed
        // TODO add your handling code here:
        alumnoMenu=5;
        AsignarCurso.banderaAsignar=2;
        
        FormDni.alumnoEmpleadoUser=1;
        panelDni();
    }//GEN-LAST:event_efectuarPagoActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        // TODO add your handling code here:
        empleadoMenu=1;
        FormDni.alumnoEmpleadoUser=2;
        panelDni();
    }//GEN-LAST:event_registrarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        empleadoMenu=2;
        FormDni.alumnoEmpleadoUser=2;
        panelDni();
    }//GEN-LAST:event_modificarActionPerformed

    private void asignarCursoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignarCursoEmpleadoActionPerformed
        // TODO add your handling code here:
        empleadoMenu=3;
        FormDni.alumnoEmpleadoUser=2;
        AsignarCursoAcargo1 acargo=new AsignarCursoAcargo1();
        Principal.principal.add(acargo);
        acargo.setVisible(true);
    }//GEN-LAST:event_asignarCursoEmpleadoActionPerformed

    private void darBajaEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darBajaEmpleadoActionPerformed
        // TODO add your handling code here:
        empleadoMenu=4;
        FormDni.alumnoEmpleadoUser=2;
        DarBajaCurso1 baja=new DarBajaCurso1();
        Principal.principal.add(baja);
        baja.setVisible(true);
    }//GEN-LAST:event_darBajaEmpleadoActionPerformed

    private void consultarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarEmpleadoActionPerformed
        // TODO add your handling code here:
        empleadoMenu=5;
        FormDni.alumnoEmpleadoUser=2;
        panelDni();
    }//GEN-LAST:event_consultarEmpleadoActionPerformed

    private void contentMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItem2ActionPerformed
        // TODO add your handling code here:
        try{
           CrearLicencia crear=new CrearLicencia();
           Principal.principal.add(crear);
           crear.setVisible(true);
        }catch(ClassNotFoundException e){
            
        }
    }//GEN-LAST:event_contentMenuItem2ActionPerformed

    private void aboutMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItem2ActionPerformed
        // TODO add your handling code here:
        AsignarLicencia asignar=new AsignarLicencia();
        Principal.principal.add(asignar);
        asignar.setVisible(true);
    }//GEN-LAST:event_aboutMenuItem2ActionPerformed

    private void aboutMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItem12ActionPerformed
        // TODO add your handling code here:
        try{
            ModificarLicencia modiLicencia=new ModificarLicencia();
            Principal.principal.add(modiLicencia);
            modiLicencia.setVisible(true);
            
        }catch(ClassNotFoundException e){
            
        }
    }//GEN-LAST:event_aboutMenuItem12ActionPerformed

    private void aboutMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItem13ActionPerformed
        // TODO add your handling code here:
        try{
            Licencia_consulta art=new Licencia_consulta();
            Principal.principal.add(art);
            art.setVisible(true);
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_aboutMenuItem13ActionPerformed

    private void contentMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItem3ActionPerformed
        // TODO add your handling code here:
        CrearCurso curso=new CrearCurso();
        Principal.principal.add(curso);
        curso.setVisible(true);
    }//GEN-LAST:event_contentMenuItem3ActionPerformed

    private void aboutMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItem15ActionPerformed
        // TODO add your handling code here:
         
        EliminarCurso curso=new EliminarCurso();
        Principal.principal.add(curso);
        curso.setVisible(true);
    }//GEN-LAST:event_aboutMenuItem15ActionPerformed

    private void aboutMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItem14ActionPerformed
        // TODO add your handling code here:
        CrearCurso.origenBandera=2;
        Horario hora=new Horario();
        Principal.principal.add(hora);
        hora.setVisible(true);
    }//GEN-LAST:event_aboutMenuItem14ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        ModificarNombre user=new ModificarNombre();
        Principal.principal.add(user);
        user.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        ModificarPass user= new ModificarPass();
        Principal.principal.add(user);
        user.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void contentMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItem4ActionPerformed
        // TODO add your handling code here:
        if(Login.usuario.getJerarquia()==1){
            try{
                CrearUsuario user=new CrearUsuario();
                Principal.principal.add(user);
                user.setVisible(true);
            }catch(ClassNotFoundException e){
                
            }
        }else{
            JOptionPane.showMessageDialog(null, "No tiene el acceso a este módulo");
        }
    }//GEN-LAST:event_contentMenuItem4ActionPerformed

    private void aboutMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItem16ActionPerformed
        // TODO add your handling code here:
        if(Login.usuario.getJerarquia()==1){
            EliminarUsuario user = new EliminarUsuario();
            Principal.principal.add(user);
            user.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "No tiene el acceso a este módulo");
        }
    }//GEN-LAST:event_aboutMenuItem16ActionPerformed

    private void aboutMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItem5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_aboutMenuItem5ActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        try {
            // TODO add your handling code here:
            Calles_consulta calle=new Calles_consulta();
            Principal.principal.add(calle);
            calle.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        try {
            // TODO add your handling code here:
            Barrio_consulta barrio=new Barrio_consulta();
            Principal.principal.add(barrio);
            barrio.setVisible(true);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void saveAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItemActionPerformed
        try {
            // TODO add your handling code here:

            Localidad_consulta localidad=new Localidad_consulta();
            Principal.principal.add(localidad);
            localidad.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_saveAsMenuItemActionPerformed

    private void aboutMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItem1ActionPerformed
        // TODO add your handling code here:
        PorCicloLectivo cl=new PorCicloLectivo();
        Principal.principal.add(cl);
        cl.setVisible(true);
    }//GEN-LAST:event_aboutMenuItem1ActionPerformed

    private void aboutMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItem9ActionPerformed
        // TODO add your handling code here:
        Deudores dr=new Deudores();
        Principal.principal.add(dr);
        dr.setVisible(true);
    }//GEN-LAST:event_aboutMenuItem9ActionPerformed

    private void aboutMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItem11ActionPerformed
        // TODO add your handling code here:
//        EgresadoDesercion ed=new EgresadoDesercion(2);
        EgresadoDesercion ed=new EgresadoDesercion();
        Principal.principal.add(ed);
        ed.setVisible(true);        
    }//GEN-LAST:event_aboutMenuItem11ActionPerformed

    void panelDni(){
        FormDni dni=new FormDni();
        Principal.principal.add(dni);
        dni.setVisible(true);
  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem1;
    private javax.swing.JMenuItem aboutMenuItem10;
    private javax.swing.JMenuItem aboutMenuItem11;
    private javax.swing.JMenuItem aboutMenuItem12;
    private javax.swing.JMenuItem aboutMenuItem13;
    private javax.swing.JMenuItem aboutMenuItem14;
    private javax.swing.JMenuItem aboutMenuItem15;
    private javax.swing.JMenuItem aboutMenuItem16;
    private javax.swing.JMenuItem aboutMenuItem2;
    private javax.swing.JMenuItem aboutMenuItem3;
    private javax.swing.JMenuItem aboutMenuItem5;
    private javax.swing.JMenuItem aboutMenuItem9;
    private javax.swing.JMenuItem asignarCurso;
    private javax.swing.JMenuItem asignarCursoEmpleado;
    private javax.swing.JMenuItem consultarAlumno;
    private javax.swing.JMenuItem consultarEmpleado;
    private javax.swing.JMenuItem contentMenuItem1;
    private javax.swing.JMenuItem contentMenuItem2;
    private javax.swing.JMenuItem contentMenuItem3;
    private javax.swing.JMenuItem contentMenuItem4;
    private javax.swing.JMenuItem darBaja;
    private javax.swing.JMenuItem darBajaEmpleado;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem efectuarPago;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem exitMenuItem1;
    private javax.swing.JMenuItem exitMenuItem10;
    private javax.swing.JMenuItem exitMenuItem2;
    private javax.swing.JMenuItem exitMenuItem3;
    private javax.swing.JMenuItem exitMenuItem4;
    private javax.swing.JMenuItem exitMenuItem5;
    private javax.swing.JMenuItem exitMenuItem6;
    private javax.swing.JMenuItem exitMenuItem7;
    private javax.swing.JMenuItem exitMenuItem8;
    private javax.swing.JMenuItem exitMenuItem9;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu helpMenu1;
    private javax.swing.JMenu helpMenu2;
    private javax.swing.JMenu helpMenu3;
    private javax.swing.JMenu helpMenu4;
    private javax.swing.JMenu helpMenu5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    public static javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem modificar;
    private javax.swing.JMenuItem modificarAlumno;
    private javax.swing.JMenuItem openMenuItem;
    public static javax.swing.JDesktopPane principal;
    private javax.swing.JMenuItem registrar;
    private javax.swing.JMenuItem registrarAlumno;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
