/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

import interfazAlumno.AsignarCurso;
import interfazAlumno.Modificar;
import interfazAlumno.DarBajaCurso;
//import interfazAlumno.Pago;
import interfazAlumno.PagoAlumno;
import interfazAlumno.PanelDni;
import interfazAlumno.EstadoAlumno;
import interfazAlumno.Inscripcion;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.Persona;
import usuario.Login;
/**
 *
 * @author araa
 */
public class AlumnoMenu extends javax.swing.JPanel {

    /**
     * Creates new form AlumnoMenu
     */
    public static int alumnoMenu=0;
    public static int pagoAlumno;
    Persona objPersona=new Persona();
    public AlumnoMenu() throws ClassNotFoundException {
        initComponents();
        
        this.setBounds(0, 45, 260, 260);
        this.setVisible(true);
    }
    
    public AlumnoMenu(Persona persona){
        initComponents();
        
        this.setBounds(0, 45, 260, 260);
        this.setVisible(true);
        
        /*if(Login.usuario.getJerarquia()==3){
            btnModificarDatos.setVisible(false);
            btnAsignarCurso.setVisible(false);
            btnPagos.setVisible(false);
            btnBajaAlumno.setVisible(false);
            
        }*/
        objPersona=persona;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnModificarDatos = new javax.swing.JButton();
        btnBajaAlumno = new javax.swing.JButton();
        btnPagos = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnAsignarCurso = new javax.swing.JButton();
        btnDarAlta = new javax.swing.JButton();

        setBackground(new java.awt.Color(239, 238, 240));

        btnModificarDatos.setText("Modificar datos");
        btnModificarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarDatosActionPerformed(evt);
            }
        });
        btnModificarDatos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnModificarDatosKeyPressed(evt);
            }
        });

        btnBajaAlumno.setText("Dar de baja a curso");
        btnBajaAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaAlumnoActionPerformed(evt);
            }
        });
        btnBajaAlumno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnBajaAlumnoKeyPressed(evt);
            }
        });

        btnPagos.setText("Efectuar pago");
        btnPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagosActionPerformed(evt);
            }
        });
        btnPagos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPagosKeyPressed(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        btnConsultar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnConsultarKeyPressed(evt);
            }
        });

        btnAsignarCurso.setText("Asignar a curso");
        btnAsignarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarCursoActionPerformed(evt);
            }
        });
        btnAsignarCurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAsignarCursoKeyPressed(evt);
            }
        });

        btnDarAlta.setText("Dar de alta");
        btnDarAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarAltaActionPerformed(evt);
            }
        });
        btnDarAlta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnDarAltaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnModificarDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnBajaAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnPagos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnConsultar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnAsignarCurso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnDarAlta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDarAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAsignarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBajaAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarDatosActionPerformed
        // TODO add your handling code here:
    /*    this.setVisible(false);
        Principal.desactivarPanel();
        
        Modificar modificar=new Modificar(objPersona);
        Principal.panelPrincipal.add(modificar);
        modificar.setVisible(true);
        */
        alumnoMenu=1;
        panelDni();
    }//GEN-LAST:event_btnModificarDatosActionPerformed

    private void btnBajaAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaAlumnoActionPerformed
        // TODO add your handling code here:
        /*this.setVisible(false);
        Principal.desactivarPanel();
        menu.Principal.menuAlumno=1;
        
        DarBajaCurso baja= new DarBajaCurso(objPersona);
        Principal.panelPrincipal.add(baja);
        baja.setVisible(true);*/
        alumnoMenu=3;
        panelDni();
    }//GEN-LAST:event_btnBajaAlumnoActionPerformed

    private void btnPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagosActionPerformed
        // TODO add your handling code here:
        AsignarCurso.banderaAsignar=2;
        
        /*this.setVisible(false);
        Principal.desactivarPanel();
        
        PagoAlumno pagos=new PagoAlumno(objPersona);
        Principal.panelPrincipal.add(pagos);
        pagos.setVisible(true);*/
        alumnoMenu=4;
        panelDni();
    }//GEN-LAST:event_btnPagosActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        /*this.setVisible(false);
        Principal.desactivarPanel();
        
        EstadoAlumno estado;
        try {
            estado = new EstadoAlumno(objPersona);
            Principal.panelPrincipal.add(estado);
            estado.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(AlumnoMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
        alumnoMenu=5;
        panelDni();
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnAsignarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarCursoActionPerformed
        // TODO add your handling code here:
        /*this.setVisible(false);
        Principal.desactivarPanel();
        Inscripcion.bandera=2;
        AsignarCurso asignar=new AsignarCurso(objPersona);
        Principal.panelPrincipal.add(asignar);
        asignar.setVisible(true);*/
        alumnoMenu=2;
        panelDni();
    }//GEN-LAST:event_btnAsignarCursoActionPerformed

    private void btnModificarDatosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnModificarDatosKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            ActionEvent e = null;
            this.btnModificarDatosActionPerformed(e);
        }
    }//GEN-LAST:event_btnModificarDatosKeyPressed

    private void btnAsignarCursoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAsignarCursoKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            ActionEvent e = null;
            this.btnAsignarCursoActionPerformed(e);
        }
    }//GEN-LAST:event_btnAsignarCursoKeyPressed

    private void btnBajaAlumnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBajaAlumnoKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            ActionEvent e = null;
            this.btnBajaAlumnoActionPerformed(e);
        }
    }//GEN-LAST:event_btnBajaAlumnoKeyPressed

    private void btnPagosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPagosKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            ActionEvent e = null;
            this.btnPagosActionPerformed(e);
        }
    }//GEN-LAST:event_btnPagosKeyPressed

    private void btnConsultarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnConsultarKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            ActionEvent e = null;
            this.btnConsultarActionPerformed(e);
        }
    }//GEN-LAST:event_btnConsultarKeyPressed

    private void btnDarAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarAltaActionPerformed
        // TODO add your handling code here:
        panelDni();
    }//GEN-LAST:event_btnDarAltaActionPerformed

    private void btnDarAltaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnDarAltaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDarAltaKeyPressed

    void panelDni(){
        this.setVisible(false);
        Principal.desactivarPanel();
       
        FormDni.alumnoEmpleadoUser=1;
        FormDni dni=new FormDni();
        Principal.panelPrincipal.add(dni);
        dni.setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarCurso;
    private javax.swing.JButton btnBajaAlumno;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnDarAlta;
    private javax.swing.JButton btnModificarDatos;
    private javax.swing.JButton btnPagos;
    // End of variables declaration//GEN-END:variables
}
