/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazEmpleado;

import Controlador.CtrlCargo;
import Controlador.CtrlCodigoPostal;
import Controlador.CtrlDomicilio;
import Controlador.CtrlEdificio;
import Controlador.CtrlEmpleado;
import Controlador.CtrlEmpleadoCargo;
import Controlador.CtrlEmpleadoTitulo;
import Controlador.CtrlFoto;
import Controlador.CtrlGremio;
import Controlador.CtrlLugar;
import Controlador.CtrlNacionalidad;
import Controlador.CtrlPersona;
import Controlador.CtrlSexo;
import Controlador.CtrlTipoDocumento;
import Controlador.CtrlTitulo;
import configuracion.Barrio_crear;
import configuracion.Calles_crear;
import configuracion.Localidad_crear;
import configuracion.Sexo_crear;
import interfazAlumno.Inscripcion;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import menu.FormDni;
import menu.Principal;
import modelo.Cargo;
import modelo.Empleado;
import modelo.Foto;
import modelo.Gremio;
import modelo.Lugar;
import modelo.Nacionalidad;
import modelo.Persona;
import modelo.Sexo;
import modelo.TipoDocumento;
import modelo.Titulo;
import usuario.CrearUsuario;
import usuario.Login;

/**
 *
 * @author araa
 */
public final class Registro extends javax.swing.JInternalFrame {

    public static int banderaEmpleado=0;
    int contadorGuardar=0;
    Connection con=clases.Conectar.conexion();
    CtrlTipoDocumento tipo = new CtrlTipoDocumento();
    CtrlLugar lugar=new CtrlLugar();
    CtrlNacionalidad nacion= new CtrlNacionalidad();
    CtrlCargo cargo=new CtrlCargo();
    CtrlTitulo titulo=new CtrlTitulo();
    CtrlGremio gremio=new CtrlGremio();
    CtrlSexo sx=new CtrlSexo();
    
    Persona personaDatos=new Persona();
    
    DefaultListModel<Cargo> modeloCargo;
    DefaultListModel<Titulo> modeloTitulo;
    
    int idEdificio=0;
    /**
     * Creates new form Registro1
     * @param cuil
     */

    public Registro(String cuil) {
        initComponents();
        
        desactivar();
        cargarComponentes();
        txtDni.setEditable(false);
        txtCuil.setText(cuil);
        obtenerDni(cuil);
    }

    public Registro(){
        initComponents();
        desactivar();
        cargarComponentes();
        txtDni.setEditable(true);
        
    }
    void cargarComponentes(){
        tipo.cargarComboTipoDocumento(cbTipoDoc);
        lugar.cargarComboLocalidad(cbLocalidad);
        lugar.cargarComboLocalidad(cbNacimiento);
        nacion.cargarComboNacionalidad(cbNacionalidad);
        cargo.cargarCombo(cbCargo);
        titulo.cargarCombo(cbTitulo);
        gremio.cargarCombo(cbGremio);
        sx.cargarCombo(cbSexo);
        
        modeloCargo=new DefaultListModel();
        modeloTitulo=new DefaultListModel();
        
        listCargo.setModel(modeloCargo);
        listTitulo.setModel(modeloTitulo);
        
        btnSiguiente.setText("Siguiente");
    }
    
    void obtenerDni(String cuil){
        String dni=cuil.substring(3, 11);
        txtDni.setText(dni);
    }
    
    void desactivar(){
        btnDeshacerCargo.setEnabled(false);
        btnDeshacerTitulo.setEnabled(false);
        
        btnAtras.setEnabled(false);
        panelContenedor.setEnabledAt(1, false);
        panelContenedor.setEnabledAt(2, false);
        btnAsignarCurso.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panelContenedor = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtCuil = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cbTipoDoc = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cbNacionalidad = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cbNacimiento = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        jLabel29 = new javax.swing.JLabel();
        cbSexo = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        txtHijos = new javax.swing.JTextField();
        btnAgregarSx = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cbLocalidad = new javax.swing.JComboBox<>();
        cbBarrio = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtFijo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        txtBloque = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtPiso = new javax.swing.JTextField();
        txtDepto = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cbCalle = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        txtCasa = new javax.swing.JTextField();
        btnLocalidad = new javax.swing.JButton();
        btnBarrio = new javax.swing.JButton();
        btnCalle = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cbGremio = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        cbCargo = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        cbTitulo = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listCargo = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        listTitulo = new javax.swing.JList<>();
        btnAsignarCargo = new javax.swing.JButton();
        btnAsignarTitulo = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        btnDeshacerCargo = new javax.swing.JButton();
        btnDeshacerTitulo = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnAsignarCurso = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        fotoPanel = new JPanelWebCam.JPanelWebCam();

        jPanel2.setBackground(new java.awt.Color(38, 86, 186));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Carga De Datos -Empleado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBackground(new java.awt.Color(220, 203, 203));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Nombre");

        txtNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });

        jLabel4.setText("Apellido");

        txtApellido.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        txtCuil.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel8.setText("CUIL");

        txtDni.setEditable(false);
        txtDni.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel17.setText("N° de documento");

        cbTipoDoc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbTipoDoc.setToolTipText("");
        cbTipoDoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTipoDocItemStateChanged(evt);
            }
        });
        cbTipoDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoDocActionPerformed(evt);
            }
        });

        jLabel13.setText("Tipo Documento");

        cbNacionalidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbNacionalidad.setToolTipText("");

        jLabel14.setText("Nacionalidad");

        cbNacimiento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbNacimiento.setToolTipText("");

        jLabel15.setText("Lugar De Nacimiento");

        jLabel5.setText("Fecha de nacimiento");

        jLabel29.setText("Sexo");

        cbSexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbSexo.setToolTipText("");

        jLabel33.setText("Personas a cargo");

        txtHijos.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        btnAgregarSx.setBackground(new java.awt.Color(38, 86, 186));
        btnAgregarSx.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgregarSx.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarSx.setText("Agregar");
        btnAgregarSx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarSxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAgregarSx)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel29))
                                .addGap(122, 122, 122))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre)
                                    .addComponent(cbTipoDoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(txtApellido)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel5)
                                        .addGap(30, 30, 30))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtDni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel4))
                                        .addGap(117, 117, 117)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(txtCuil, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel8)))
                                    .addComponent(jLabel15)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(cbNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtHijos, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel33)))
                                .addGap(61, 61, 61))))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel17)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCuil, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAgregarSx)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHijos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        panelContenedor.addTab("Datos personales", jPanel5);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Localidad");

        cbLocalidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbLocalidad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLocalidadItemStateChanged(evt);
            }
        });

        cbBarrio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbBarrio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbBarrioItemStateChanged(evt);
            }
        });

        jLabel19.setText("Barrio");

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "contactos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel11.setText("Celular");

        txtCelular.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCelularKeyPressed(evt);
            }
        });

        jLabel18.setText("Telefono Fijo");

        txtFijo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtFijo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFijoKeyPressed(evt);
            }
        });

        jLabel10.setText("Correo");

        txtCorreo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFijo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Edificio"));

        txtBloque.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtBloque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBloqueKeyPressed(evt);
            }
        });

        jLabel22.setText("Bloque");

        jLabel23.setText("Piso");

        txtPiso.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtPiso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPisoKeyPressed(evt);
            }
        });

        txtDepto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel32.setText("N° dto.");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDepto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBloque, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBloque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txtDepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel21.setText("Calle/Manzana:");

        cbCalle.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCalleActionPerformed(evt);
            }
        });

        jLabel20.setText("N° de casa/lote:");

        txtCasa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        btnLocalidad.setBackground(new java.awt.Color(38, 86, 186));
        btnLocalidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLocalidad.setForeground(new java.awt.Color(255, 255, 255));
        btnLocalidad.setText("Agregar");
        btnLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalidadActionPerformed(evt);
            }
        });

        btnBarrio.setBackground(new java.awt.Color(38, 86, 186));
        btnBarrio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBarrio.setForeground(new java.awt.Color(255, 255, 255));
        btnBarrio.setText("Agregar");
        btnBarrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarrioActionPerformed(evt);
            }
        });

        btnCalle.setBackground(new java.awt.Color(38, 86, 186));
        btnCalle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalle.setForeground(new java.awt.Color(255, 255, 255));
        btnCalle.setText("Agregar");
        btnCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalleActionPerformed(evt);
            }
        });

        jLabel16.setText("Código postal");

        txtCodigo.setEditable(false);
        txtCodigo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbBarrio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbCalle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(btnLocalidad)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBarrio)
                                    .addComponent(btnCalle))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(52, 52, 52))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLocalidad)
                            .addComponent(jLabel16)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBarrio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCalle))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelContenedor.addTab("Domicilio", jPanel7);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("Gremio");

        cbGremio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel25.setText("Cargo");

        cbCargo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel26.setText("Titulo");

        cbTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbTitulo.setToolTipText("");

        jScrollPane3.setViewportView(listCargo);

        jScrollPane4.setViewportView(listTitulo);

        btnAsignarCargo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnAsignarCargo.setText(">");
        btnAsignarCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarCargoActionPerformed(evt);
            }
        });

        btnAsignarTitulo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnAsignarTitulo.setText(">");
        btnAsignarTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarTituloActionPerformed(evt);
            }
        });

        jLabel27.setText("Cargos seleccionados");

        jLabel28.setText("Titulos seleccionados");

        btnDeshacerCargo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnDeshacerCargo.setText("<");
        btnDeshacerCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeshacerCargoActionPerformed(evt);
            }
        });

        btnDeshacerTitulo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnDeshacerTitulo.setText("<");
        btnDeshacerTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeshacerTituloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel12Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(cbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(btnAsignarCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(btnDeshacerCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(cbGremio, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnAsignarTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeshacerTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbGremio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAsignarCargo)
                        .addComponent(btnDeshacerCargo))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAsignarTitulo)
                            .addComponent(btnDeshacerTitulo))
                        .addGap(61, 61, 61)))
                .addGap(37, 37, 37))
        );

        panelContenedor.addTab("Otros datos", jPanel12);

        btnAtras.setBackground(new java.awt.Color(38, 86, 186));
        btnAtras.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnSiguiente.setBackground(new java.awt.Color(38, 86, 186));
        btnSiguiente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnAsignarCurso.setBackground(new java.awt.Color(38, 86, 186));
        btnAsignarCurso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAsignarCurso.setForeground(new java.awt.Color(255, 255, 255));
        btnAsignarCurso.setText("Asignar cursos");
        btnAsignarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarCursoActionPerformed(evt);
            }
        });

        btncancelar.setBackground(new java.awt.Color(38, 86, 186));
        btncancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fotoPanelLayout = new javax.swing.GroupLayout(fotoPanel);
        fotoPanel.setLayout(fotoPanelLayout);
        fotoPanelLayout.setHorizontalGroup(
            fotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        fotoPanelLayout.setVerticalGroup(
            fotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 201, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                    .addComponent(fotoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAsignarCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelContenedor)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fotoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addComponent(btnAsignarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbBarrioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbBarrioItemStateChanged
        // TODO add your handling code here:
        
        if(evt.getStateChange()== ItemEvent.SELECTED){
            if(cbBarrio.getSelectedIndex()!=0){
                Lugar item=new Lugar();
                item=(Lugar)cbBarrio.getSelectedItem();
                DefaultComboBoxModel modelo=new DefaultComboBoxModel(lugar.cargarFiltrado(item.getIdLugar(),1));
            
                cbCalle.setModel(modelo);
                
            }
        }
 
    }//GEN-LAST:event_cbBarrioItemStateChanged

    private void cbLocalidadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbLocalidadItemStateChanged
        // TODO add your handling code here:
         if(evt.getStateChange()==ItemEvent.SELECTED){
            if(cbLocalidad.getSelectedIndex()!=0){
                Lugar item;
                item=(Lugar)cbLocalidad.getSelectedItem();           
                DefaultComboBoxModel modelo=new DefaultComboBoxModel(lugar.cargarFiltrado(item.getIdLugar(), 2));
            
                cbBarrio.setModel(modelo);
                
                CtrlCodigoPostal cod=new CtrlCodigoPostal();
                
                txtCodigo.setText(String.valueOf(cod.leer(item.getIdLugar())));
            }
        }
        
    }//GEN-LAST:event_cbLocalidadItemStateChanged

    private void cbTipoDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoDocActionPerformed

    private void btnAsignarTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarTituloActionPerformed
        // TODO add your handling code here:
        if(cbTitulo.getSelectedIndex()!= 0){
            modeloTitulo.addElement((Titulo) cbTitulo.getSelectedItem());
            cbTitulo.removeItem(cbTitulo.getSelectedItem());
            cbTitulo.setSelectedIndex(0);
            
            btnDeshacerTitulo.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(null, "Necesita seleccionar un titulo");
        }
    }//GEN-LAST:event_btnAsignarTituloActionPerformed

    private void btnDeshacerTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeshacerTituloActionPerformed
        // TODO add your handling code here:
        if(listTitulo.getSelectedIndex()!= -1){
            cbTitulo.addItem(listTitulo.getSelectedValue());
            modeloTitulo.remove(listTitulo.getSelectedIndex());
            
        }
        
        if(modeloTitulo.isEmpty()){
            btnDeshacerTitulo.setEnabled(false);
        }
    }//GEN-LAST:event_btnDeshacerTituloActionPerformed

    private void btnDeshacerCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeshacerCargoActionPerformed
        // TODO add your handling code here:
        if(listCargo.getSelectedIndex()!= -1){
            cbCargo.addItem(listCargo.getSelectedValue());
            modeloCargo.remove(listCargo.getSelectedIndex());
        }
        
        if(modeloCargo.isEmpty()){
            btnDeshacerCargo.setEnabled(false);
        }
    }//GEN-LAST:event_btnDeshacerCargoActionPerformed

    private void btnAsignarCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarCargoActionPerformed
        // TODO add your handling code here:
        
        if(cbCargo.getSelectedIndex()!=0){
            
            modeloCargo.addElement((Cargo) cbCargo.getSelectedItem());
            cbCargo.removeItem(cbCargo.getSelectedItem());
            cbCargo.setSelectedIndex(0);
            
            btnDeshacerCargo.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(null, "Necesita seleccionar una opción");
        }
    }//GEN-LAST:event_btnAsignarCargoActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:

        switch(panelContenedor.getSelectedIndex()){

            case 1:
            panelContenedor.setEnabledAt(0, true);
            panelContenedor.setSelectedIndex(0);
            panelContenedor.setEnabledAt(1, false);

            btnAtras.setEnabled(false);
            break;

            case 2:
            panelContenedor.setEnabledAt(1, true);
            panelContenedor.setSelectedIndex(1);
            panelContenedor.setEnabledAt(2, false);
            break;
        }

    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        switch(panelContenedor.getSelectedIndex()){
            case 0:

            if(cbTipoDoc.getSelectedIndex()==0 || txtDni.getText().equals("") || txtCuil.getText().equals("") || txtNombre.getText().equals("")
                || txtApellido.getText().equals("") || cbNacimiento.getSelectedIndex()==0 || cbNacionalidad.getSelectedIndex()==0){

                JOptionPane.showMessageDialog(null, "Faltan datos qué ingresar");
            }else{
                panelContenedor.setEnabledAt(1, true);
                panelContenedor.setSelectedIndex(1);
                panelContenedor.setEnabledAt(0, false);

                btnAtras.setEnabled(true);
            }

            break;

            case 1:
                if(contadorGuardar==0){
                    if (cbLocalidad.getSelectedIndex() == 0 || cbBarrio.getSelectedIndex() == 0 || cbCalle.getSelectedIndex() == 0) {
                        JOptionPane.showMessageDialog(null, "Le falta completar domicilio: seleccionar localidad, barrio y/o calle");

                    } else {

                        if (txtCelular.getText().equalsIgnoreCase("") || txtFijo.getText().equalsIgnoreCase("")
                                || txtCorreo.getText().equalsIgnoreCase("")) {
                            if (JOptionPane.showConfirmDialog(null, "Está dejando vacíos campos de celular, teléfono fijo o correo ¿Quiere continuar sin agregarlos?", "", +JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

                                panelContenedor.setEnabledAt(2, true);
                                panelContenedor.setSelectedIndex(2);
                                panelContenedor.setEnabledAt(1, false);

                                //btnSiguiente.setText("Guardar");

                            }
                        } else {

                            panelContenedor.setEnabledAt(2, true);
                            panelContenedor.setSelectedIndex(2);
                            panelContenedor.setEnabledAt(1, false);

//                            btnSiguiente.setText("Guardar");
                        }
                    }                    
                }else{
                    panelContenedor.setEnabledAt(2, true);
                    panelContenedor.setSelectedIndex(2);
                    panelContenedor.setEnabledAt(1, false);
                }

        break;

        case 2:
            if(contadorGuardar==0){
                btnSiguiente.setText("Terminar");
                guardar();
            }else{
                btnSiguiente.setEnabled(false);
            }

        break;

        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    void guardar(){
        CtrlDomicilio domicilioId=new CtrlDomicilio();
        CtrlEdificio edificio=new CtrlEdificio();
        CtrlPersona personaCrear=new CtrlPersona();
        CtrlEmpleado ctrlEmpleado=new CtrlEmpleado();
        CtrlEmpleadoCargo ctrlEmpleadoCargo=new CtrlEmpleadoCargo();
        CtrlEmpleadoTitulo ctrlEmpleadoTitulo=new CtrlEmpleadoTitulo();
        CtrlFoto ctrlFoto = new CtrlFoto();
        
        TipoDocumento documento=(TipoDocumento) cbTipoDoc.getSelectedItem();
        Lugar nacimiento=(Lugar) cbNacimiento.getSelectedItem();
        Nacionalidad nacionalidad=(Nacionalidad) cbNacionalidad.getSelectedItem();
        Lugar calle=(Lugar)cbCalle.getSelectedItem();
        Empleado empleadoNew=new Empleado();
        byte[] imagen = fotoPanel.getBytes();

        int hijos=0;
        
        if(modeloCargo.isEmpty() || modeloTitulo.isEmpty()){
            JOptionPane.showMessageDialog(null, "No ha seleccionado un cargo y/o título del empleado");
        }else{
            
        //SE VERIFICA SI SE INGRESÓ ALGO CORRESPONDIENTE DE EDIFICIO..
            if(!txtBloque.getText().equals("") && !txtPiso.getText().equals("") && !txtDepto.getText().equals("")){
                edificio.crear(txtBloque.getText(), txtPiso.getText(), txtDepto.getText());
                idEdificio=edificio.leer().getIdEdificio();
            }

        //<SE CREA UN DOMICILIO...
            domicilioId.crear(Integer.parseInt(txtCasa.getText()), txtFijo.getText(), calle.getIdLugar(), idEdificio);

        //<SE CREA REGISTRO DE FOTO Y TRAE EL ULTIMO id
            Foto foto = new Foto();
    
            ctrlFoto.crear(imagen);
            foto = (Foto) ctrlFoto.leerUltimaFoto();
       
        //<AQUI SE DA DE ALTA UNA PERSONA..
            if(txtHijos.getText().equals("")){
                hijos=0;
            }else{
                hijos=Integer.parseInt(txtHijos.getText());
            }
            Sexo item=(Sexo) cbSexo.getSelectedItem();
            personaCrear.crear(txtNombre.getText(), txtApellido.getText(), fecha.getDate(), item.getIdSexo(), txtCuil.getText(), hijos, txtCorreo.getText(), txtCelular.getText(), domicilioId.leer().getIdDomicilio(), documento.getIdTipoDocumento(), nacionalidad.getIdNacionalidad(), foto.getIdFoto(), nacimiento.getIdLugar(), false);

            personaDatos=personaCrear.leer(txtCuil.getText());
        
        //SE CREA UN REGISTRO EN LA TABLA EMPLEADO
            java.util.Date fechaHoy=new Date();
            Gremio itemGremio;
            int idGremio=0;
            if(cbGremio.getSelectedIndex()==0){
                idGremio=0;
            }else{
                itemGremio=(Gremio) cbGremio.getSelectedItem();
                idGremio=itemGremio.getIdGremio();
            }
            
            if(personaDatos.getIdPersona()!=0){
                //JOptionPane.showMessageDialog(null, "Los datos se guardaron");
            
                ctrlEmpleado.crear(fechaHoy, personaDatos.getIdPersona(), 1, idGremio);
                empleadoNew = ctrlEmpleado.leer(personaDatos.getIdPersona());

                if(empleadoNew.getIdEmpleado()!=0){
                    //LOS ListModel SON PARA PODER SACAR EL TAMAÑO DE LAS LISTAS, PODER RECORRERLAS Y PODER ACCEDER AL ID DE CADA OBJETO GUARDADO
                    ListModel<Cargo> listaCargo = listCargo.getModel();
                    ListModel<Titulo> listaTitulo = listTitulo.getModel();

                    for (int i = 0; i < listaCargo.getSize(); i++) {
                        ctrlEmpleadoCargo.crear(listaCargo.getElementAt(i).getIdCargo(), ctrlEmpleado.leerIdEmpleado(empleadoNew.getIdEmpleado()).getIdEmpleado());
                    }
                    for (int i = 0; i < listaTitulo.getSize(); i++) {
                        ctrlEmpleadoTitulo.crear(listaTitulo.getElementAt(i).getIdTitulo(), ctrlEmpleado.leerIdEmpleado(empleadoNew.getIdEmpleado()).getIdEmpleado());
                    }
                    
                    JOptionPane.showMessageDialog(null, "Los datos se guardaron");
                    
                    btnSiguiente.setText("Siguiente");
                    contadorGuardar++;
                    btnSiguiente.setEnabled(true);
                    btnAsignarCurso.setEnabled(true);
                    panelContenedor.setSelectedIndex(0);
                    panelContenedor.setEnabledAt(2, false);
                    btnAtras.setEnabled(false);
                }else{
                    JOptionPane.showMessageDialog(null,"No se pudo guardar los datos");
                }
                
            }else{
                JOptionPane.showMessageDialog(null, "No se pudo guardar los datos");
                return;
            }
       
            if(FormDni.alumnoEmpleadoUser == 3) {

                try{
                    this.setVisible(false);
                    CrearUsuario crear = new CrearUsuario(personaDatos);
                    Principal.panelPrincipal.add(crear);
                    //this.setComponentZOrder(crear, 0);

                    crear.setVisible(true);

                }catch (ClassNotFoundException ex) {
                    Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

        
    }    
    private void btnAsignarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarCursoActionPerformed
        // TODO add your handling code here:
        banderaEmpleado=1;
        
        AsignarCursoAcargo asignar=new AsignarCursoAcargo(personaDatos);
        
        Principal.panelPrincipal.add(asignar);
        this.setComponentZOrder(asignar, 0);
        this.isOptimizedDrawingEnabled();
        asignar.setVisible(true);

    }//GEN-LAST:event_btnAsignarCursoActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        
        if(FormDni.alumnoEmpleadoUser==3){
            dispose();
            Login log=new Login();
            Principal.panelPrincipal.add(log);
            log.setVisible(true);
        }else{    
            Principal.activarPanel();
            dispose();
        }
    }//GEN-LAST:event_btncancelarActionPerformed

    @Override
    public boolean isOptimizedDrawingEnabled(){
        return false;
    }
    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnAgregarSxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSxActionPerformed
        // TODO add your handling code here:
        try {
    //ESTA BANDERA ES PARA SABER SI, EN CASO DE CANCELAR, SE DEBA ACTIVAR LOS PANELES DEL MENU PRINCIPAL O NO..        
            Sexo_crear.sxBandera=1;
            
            Sexo_crear sxC = new Sexo_crear();
            Principal.panelPrincipal.add(sxC);
            this.setComponentZOrder(sxC, 0);
            sxC.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Inscripcion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAgregarSxActionPerformed

    private void cbTipoDocItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTipoDocItemStateChanged
        // TODO add your handling code here:
        txtNombre.requestFocus();
    }//GEN-LAST:event_cbTipoDocItemStateChanged

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtApellido.requestFocus();
        }
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtBloqueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBloqueKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtPiso.requestFocus();
        }
    }//GEN-LAST:event_txtBloqueKeyPressed

    private void txtPisoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPisoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtDepto.requestFocus();
        }
    }//GEN-LAST:event_txtPisoKeyPressed

    private void txtCelularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtFijo.requestFocus();
        }
    }//GEN-LAST:event_txtCelularKeyPressed

    private void txtFijoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFijoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtCorreo.requestFocus();
        }
    }//GEN-LAST:event_txtFijoKeyPressed

    private void cbCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCalleActionPerformed

    private void btnLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalidadActionPerformed
        // TODO add your handling code here:
        try {
            Localidad_crear crear = new Localidad_crear();
            Principal.panelPrincipal.add(crear);
            this.setComponentZOrder(crear, 0);
            crear.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Inscripcion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLocalidadActionPerformed

    private void btnBarrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarrioActionPerformed
        // TODO add your handling code here:
         try {
            Barrio_crear crear=new Barrio_crear();
            Principal.panelPrincipal.add(crear);
            this.setComponentZOrder(crear, 0);
            crear.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Inscripcion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBarrioActionPerformed

    private void btnCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalleActionPerformed
        // TODO add your handling code here:
         try {
            Calles_crear crear=new Calles_crear();
            Principal.panelPrincipal.add(crear);
            this.setComponentZOrder(crear, 0);
            crear.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Inscripcion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCalleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarSx;
    private javax.swing.JButton btnAsignarCargo;
    private javax.swing.JButton btnAsignarCurso;
    private javax.swing.JButton btnAsignarTitulo;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBarrio;
    private javax.swing.JButton btnCalle;
    private javax.swing.JButton btnDeshacerCargo;
    private javax.swing.JButton btnDeshacerTitulo;
    private javax.swing.JButton btnLocalidad;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btncancelar;
    private javax.swing.JComboBox<Lugar> cbBarrio;
    private javax.swing.JComboBox<Lugar> cbCalle;
    private javax.swing.JComboBox<Cargo> cbCargo;
    private javax.swing.JComboBox<Gremio> cbGremio;
    private javax.swing.JComboBox<Lugar> cbLocalidad;
    private javax.swing.JComboBox<Lugar> cbNacimiento;
    private javax.swing.JComboBox<Nacionalidad> cbNacionalidad;
    private javax.swing.JComboBox<Sexo> cbSexo;
    private javax.swing.JComboBox<TipoDocumento> cbTipoDoc;
    private javax.swing.JComboBox<Titulo> cbTitulo;
    private com.toedter.calendar.JDateChooser fecha;
    private JPanelWebCam.JPanelWebCam fotoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<Cargo> listCargo;
    private javax.swing.JList<Titulo> listTitulo;
    private javax.swing.JPanel panel;
    private javax.swing.JTabbedPane panelContenedor;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBloque;
    private javax.swing.JTextField txtCasa;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCuil;
    private javax.swing.JTextField txtDepto;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtFijo;
    private javax.swing.JTextField txtHijos;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPiso;
    // End of variables declaration//GEN-END:variables
}
