/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazAlumno;

import Controlador.CtrlAlumno;
import Controlador.CtrlCodigoPostal;
import Controlador.CtrlDomicilio;
import Controlador.CtrlEdificio;
import Controlador.CtrlFoto;
import Controlador.CtrlLugar;
import Controlador.CtrlNacionalidad;
import Controlador.CtrlPersona;
import Controlador.CtrlPersonaTrabajo;
import Controlador.CtrlPlanPersona;
import Controlador.CtrlPlanes;
import Controlador.CtrlSexo;
import Controlador.CtrlTipoCurso;
import Controlador.CtrlTipoDocumento;
import Controlador.CtrlTrabajo;
import com.sun.glass.events.KeyEvent;
import configuracion.Barrio_crear;
import configuracion.Calles_crear;
import configuracion.Localidad_crear;
import configuracion.Sexo_crear;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import principal.Principal;
import modelo.Foto;
import modelo.Nacionalidad;
import modelo.Planes;
import modelo.TipoCurso;
import modelo.TipoDocumento;
import modelo.Trabajo;
import modelo.Lugar;
import modelo.Persona;
import modelo.Sexo;
/**
 *
 * @author
 */
public final class Inscripcion extends javax.swing.JInternalFrame {
    
    public static int bandera=0;
    public static int banderaInscripcionLugar=0;
    int contadorGuardar=0;
    Connection con = clases.Conectar.conexion();
    CtrlTipoDocumento tipo = new CtrlTipoDocumento();
    CtrlLugar lugar=new CtrlLugar();
    CtrlNacionalidad nacion= new CtrlNacionalidad();
    CtrlTrabajo trabajo=new CtrlTrabajo();
    CtrlPlanes planes=new CtrlPlanes();
    CtrlTipoCurso tipoCurso=new CtrlTipoCurso();
    CtrlSexo sx=new CtrlSexo();
    Persona personaDatos=new Persona();
    
    int idEdificio=0;
    
    DefaultListModel<Planes> modeloPlan;
    DefaultListModel<Trabajo> modeloTrabajo;
    //DefaultListModel<TipoCurso> modeloCursos;
    DefaultListModel<TipoCurso>modeloDisponible;
    
    /**
     * Creates new form InscripcionAlumno
     * @param cuil
     * @throws java.lang.ClassNotFoundException
     */
    public Inscripcion(String cuil) throws ClassNotFoundException {
       initComponents();
       
       tipo.cargarComboTipoDocumento(cbTipo);
       lugar.cargarComboLocalidad(cbLocalidad);
       lugar.cargarComboLocalidad(cbNacimiento);
       nacion.cargarComboNacionalidad(cbNacionalidad);
       trabajo.cargarComboTrabajo(cbTrabajo);
       planes.cargarComboPlan(cbPlan);
       sx.cargarCombo(cbSexo);
       
       modeloPlan=new DefaultListModel();
       modeloTrabajo=new DefaultListModel();
       //modeloCursos=new DefaultListModel();
       
       listPlan.setModel(modeloPlan);
       listTrabajo.setModel(modeloTrabajo);
      
       desactivar();
      
       btnSiguiente.setText("Siguiente");
       btnCancelar.setText("Cancelar");
       txtCuil.setText(cuil);
       obtenerDni(cuil);
       
       cbTipo.requestFocus();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelContenedor = new javax.swing.JTabbedPane();
        panelInscripcion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtCuil = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbNacionalidad = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cbNacimiento = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        cbTipo = new javax.swing.JComboBox<>();
        cbSexo = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        btnAgregarSx = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        txtHijos = new javax.swing.JTextField();
        btnActualizarNacionalidad = new javax.swing.JButton();
        btnActualizarTipoDoc = new javax.swing.JButton();
        btnActualizarSexo = new javax.swing.JButton();
        btnActualizarLugarNac = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cbLocalidad = new javax.swing.JComboBox<>();
        cbBarrio = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtFijo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        cbCalle = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        txtBloque = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtPiso = new javax.swing.JTextField();
        txtDepto = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtCasa = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnLocalidad = new javax.swing.JButton();
        btnBarrio = new javax.swing.JButton();
        btnCalle = new javax.swing.JButton();
        btnActualizarCalle = new javax.swing.JButton();
        btnActualizarLocalidad = new javax.swing.JButton();
        btnActualizarBarrio = new javax.swing.JButton();
        panelOtros = new javax.swing.JPanel();
        cbPlan = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cbTrabajo = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listPlan = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        listTrabajo = new javax.swing.JList<>();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        btnAsignarTrabajo = new javax.swing.JButton();
        btnDeshacerTrabajo = new javax.swing.JButton();
        btnDeshacerPlanes = new javax.swing.JButton();
        btnAsignarPlan = new javax.swing.JButton();
        btnActualizarTrabajo = new javax.swing.JButton();
        btnActualizarPlanes = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        fotoPanel = new JPanelWebCam.JPanelWebCam();
        btnAtras = new javax.swing.JButton();
        btnAsignarCurso = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(220, 203, 203));

        panelInscripcion.setBackground(new java.awt.Color(255, 255, 255));
        panelInscripcion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Nombre");

        txtNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });

        jLabel4.setText("Apellido");

        txtApellido.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApellidoKeyPressed(evt);
            }
        });

        txtCuil.setToolTipText("SEPARAR CON - (guiones) Y SIN ESPACIOS\nPor ejemplo: XX-12345678-XX");
        txtCuil.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel8.setText("CUIL");

        txtDni.setEditable(false);
        txtDni.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel17.setText("N° de documento");

        jLabel13.setText("Tipo Documento");

        cbNacionalidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbNacionalidad.setToolTipText("");

        jLabel14.setText("Nacionalidad");

        cbNacimiento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbNacimiento.setToolTipText("");

        jLabel15.setText("Lugar De Nacimiento");

        jLabel5.setText("Fecha de nacimiento");

        cbTipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbTipo.setToolTipText("");
        cbTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTipoItemStateChanged(evt);
            }
        });

        cbSexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbSexo.setToolTipText("");

        jLabel29.setText("Sexo");

        btnAgregarSx.setBackground(new java.awt.Color(38, 86, 186));
        btnAgregarSx.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgregarSx.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarSx.setText("Agregar");
        btnAgregarSx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarSxActionPerformed(evt);
            }
        });

        jLabel25.setText("Personas a cargo");

        txtHijos.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        btnActualizarNacionalidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar(2).png"))); // NOI18N
        btnActualizarNacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarNacionalidadActionPerformed(evt);
            }
        });

        btnActualizarTipoDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar(2).png"))); // NOI18N
        btnActualizarTipoDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarTipoDocActionPerformed(evt);
            }
        });

        btnActualizarSexo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar(2).png"))); // NOI18N
        btnActualizarSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarSexoActionPerformed(evt);
            }
        });

        btnActualizarLugarNac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar(2).png"))); // NOI18N
        btnActualizarLugarNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarLugarNacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInscripcionLayout = new javax.swing.GroupLayout(panelInscripcion);
        panelInscripcion.setLayout(panelInscripcionLayout);
        panelInscripcionLayout.setHorizontalGroup(
            panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInscripcionLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel13)
                .addGap(10, 10, 10)
                .addComponent(btnActualizarTipoDoc)
                .addGap(118, 118, 118)
                .addComponent(jLabel17)
                .addGap(82, 82, 82)
                .addComponent(jLabel8))
            .addGroup(panelInscripcionLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(txtCuil, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelInscripcionLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addGap(219, 219, 219)
                .addComponent(jLabel4)
                .addGap(174, 174, 174)
                .addComponent(jLabel5))
            .addGroup(panelInscripcionLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelInscripcionLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel29)
                .addGap(12, 12, 12)
                .addComponent(btnActualizarSexo)
                .addGap(219, 219, 219)
                .addComponent(jLabel15)
                .addGap(4, 4, 4)
                .addComponent(btnActualizarLugarNac))
            .addGroup(panelInscripcionLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnAgregarSx)
                .addGap(71, 71, 71)
                .addComponent(cbNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelInscripcionLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel14)
                .addGap(7, 7, 7)
                .addComponent(btnActualizarNacionalidad)
                .addGap(169, 169, 169)
                .addComponent(jLabel25))
            .addGroup(panelInscripcionLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(cbNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addComponent(txtHijos, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelInscripcionLayout.setVerticalGroup(
            panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInscripcionLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActualizarTipoDoc)
                    .addGroup(panelInscripcionLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel17)
                            .addComponent(jLabel8))))
                .addGap(5, 5, 5)
                .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCuil, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(3, 3, 3)
                .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelInscripcionLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22)
                .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActualizarSexo)
                    .addComponent(btnActualizarLugarNac)
                    .addGroup(panelInscripcionLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel15))))
                .addGap(4, 4, 4)
                .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarSx)
                    .addGroup(panelInscripcionLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInscripcionLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel25))
                    .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel14)
                        .addComponent(btnActualizarNacionalidad)))
                .addGap(6, 6, 6)
                .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHijos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panelContenedor.addTab("Datos personales", panelInscripcion);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Localidad");

        cbLocalidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbLocalidad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLocalidadItemStateChanged(evt);
            }
        });

        cbBarrio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbBarrio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbBarrioItemStateChanged(evt);
            }
        });

        jLabel19.setText("Barrio:");

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "contactos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel11.setText("Celular");

        txtCelular.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCelularKeyPressed(evt);
            }
        });

        jLabel18.setText("Telefono Fijo");

        txtFijo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtFijo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFijoKeyPressed(evt);
            }
        });

        jLabel10.setText("Correo");

        txtCorreo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFijo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel21.setText("Calle/Manzana:");

        cbCalle.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Edificio"));

        txtBloque.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtBloque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBloqueKeyPressed(evt);
            }
        });

        jLabel22.setText("Bloque");

        jLabel23.setText("Piso");

        txtPiso.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtPiso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPisoKeyPressed(evt);
            }
        });

        txtDepto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel32.setText("N° dto.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDepto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBloque, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBloque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txtDepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel20.setText("N° de casa/lote:");

        txtCasa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel16.setText("Código postal");

        txtCodigo.setEditable(false);
        txtCodigo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        btnLocalidad.setBackground(new java.awt.Color(38, 86, 186));
        btnLocalidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLocalidad.setForeground(new java.awt.Color(255, 255, 255));
        btnLocalidad.setText("Agregar");
        btnLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalidadActionPerformed(evt);
            }
        });

        btnBarrio.setBackground(new java.awt.Color(38, 86, 186));
        btnBarrio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBarrio.setForeground(new java.awt.Color(255, 255, 255));
        btnBarrio.setText("Agregar");
        btnBarrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarrioActionPerformed(evt);
            }
        });

        btnCalle.setBackground(new java.awt.Color(38, 86, 186));
        btnCalle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalle.setForeground(new java.awt.Color(255, 255, 255));
        btnCalle.setText("Agregar");
        btnCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalleActionPerformed(evt);
            }
        });

        btnActualizarCalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar(2).png"))); // NOI18N
        btnActualizarCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarCalleActionPerformed(evt);
            }
        });

        btnActualizarLocalidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar(2).png"))); // NOI18N
        btnActualizarLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarLocalidadActionPerformed(evt);
            }
        });

        btnActualizarBarrio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar(2).png"))); // NOI18N
        btnActualizarBarrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarBarrioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnActualizarLocalidad)
                .addGap(8, 8, 8)
                .addComponent(jLabel6))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActualizarBarrio)
                    .addComponent(btnActualizarCalle))
                .addGap(8, 8, 8)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(12, 12, 12)
                        .addComponent(txtCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLocalidad)
                    .addComponent(btnBarrio)
                    .addComponent(btnCalle))
                .addGap(95, 95, 95)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(38, 38, 38)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActualizarLocalidad)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6)))
                .addGap(4, 4, 4)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnActualizarBarrio)
                        .addGap(38, 38, 38)
                        .addComponent(btnActualizarCalle))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cbLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel19)
                        .addGap(8, 8, 8)
                        .addComponent(cbBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel21)
                        .addGap(7, 7, 7)
                        .addComponent(cbCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(txtCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnLocalidad)
                        .addGap(37, 37, 37)
                        .addComponent(btnBarrio)
                        .addGap(36, 36, 36)
                        .addComponent(btnCalle))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelContenedor.addTab("Domicilio", jPanel7);

        panelOtros.setBackground(new java.awt.Color(255, 255, 255));

        cbPlan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPlanActionPerformed(evt);
            }
        });

        jLabel7.setText("Planes");

        jLabel26.setText("Trabajo");

        cbTrabajo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbTrabajo.setToolTipText("");

        jScrollPane3.setViewportView(listPlan);

        jScrollPane4.setViewportView(listTrabajo);

        jLabel27.setText("Planes que posee");

        jLabel28.setText("Trabajos actuales");

        btnAsignarTrabajo.setBackground(new java.awt.Color(38, 86, 186));
        btnAsignarTrabajo.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        btnAsignarTrabajo.setForeground(new java.awt.Color(255, 255, 255));
        btnAsignarTrabajo.setText("Asignar");
        btnAsignarTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarTrabajoActionPerformed(evt);
            }
        });

        btnDeshacerTrabajo.setBackground(new java.awt.Color(38, 86, 186));
        btnDeshacerTrabajo.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        btnDeshacerTrabajo.setForeground(new java.awt.Color(255, 255, 255));
        btnDeshacerTrabajo.setText("<");
        btnDeshacerTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeshacerTrabajoActionPerformed(evt);
            }
        });

        btnDeshacerPlanes.setBackground(new java.awt.Color(38, 86, 186));
        btnDeshacerPlanes.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        btnDeshacerPlanes.setForeground(new java.awt.Color(255, 255, 255));
        btnDeshacerPlanes.setText("<");
        btnDeshacerPlanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeshacerPlanesActionPerformed(evt);
            }
        });

        btnAsignarPlan.setBackground(new java.awt.Color(38, 86, 186));
        btnAsignarPlan.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        btnAsignarPlan.setForeground(new java.awt.Color(255, 255, 255));
        btnAsignarPlan.setText("Asignar");
        btnAsignarPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarPlanActionPerformed(evt);
            }
        });

        btnActualizarTrabajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar(2).png"))); // NOI18N
        btnActualizarTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarTrabajoActionPerformed(evt);
            }
        });

        btnActualizarPlanes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar(2).png"))); // NOI18N
        btnActualizarPlanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPlanesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOtrosLayout = new javax.swing.GroupLayout(panelOtros);
        panelOtros.setLayout(panelOtrosLayout);
        panelOtrosLayout.setHorizontalGroup(
            panelOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOtrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOtrosLayout.createSequentialGroup()
                        .addGroup(panelOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelOtrosLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnActualizarTrabajo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelOtrosLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(cbTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAsignarTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(btnDeshacerTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panelOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOtrosLayout.createSequentialGroup()
                        .addGroup(panelOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelOtrosLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnActualizarPlanes)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelOtrosLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(cbPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAsignarPlan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDeshacerPlanes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panelOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelOtrosLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel27)))))
                .addContainerGap())
        );
        panelOtrosLayout.setVerticalGroup(
            panelOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOtrosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel27)
                        .addComponent(jLabel7))
                    .addComponent(btnActualizarPlanes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDeshacerPlanes)
                        .addComponent(btnAsignarPlan)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(panelOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOtrosLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOtrosLayout.createSequentialGroup()
                        .addGroup(panelOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26)
                            .addComponent(btnActualizarTrabajo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeshacerTrabajo)
                            .addComponent(btnAsignarTrabajo))
                        .addGap(67, 67, 67)))
                .addGap(39, 39, 39))
        );

        panelContenedor.addTab("Otros datos", panelOtros);

        btnSiguiente.setBackground(new java.awt.Color(38, 86, 186));
        btnSiguiente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(38, 86, 186));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fotoPanelLayout = new javax.swing.GroupLayout(fotoPanel);
        fotoPanel.setLayout(fotoPanelLayout);
        fotoPanelLayout.setHorizontalGroup(
            fotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );
        fotoPanelLayout.setVerticalGroup(
            fotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 201, Short.MAX_VALUE)
        );

        btnAtras.setBackground(new java.awt.Color(38, 86, 186));
        btnAtras.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnAsignarCurso.setBackground(new java.awt.Color(38, 86, 186));
        btnAsignarCurso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAsignarCurso.setForeground(new java.awt.Color(255, 255, 255));
        btnAsignarCurso.setText("Asignar cursos");
        btnAsignarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fotoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                    .addComponent(btnAsignarCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelContenedor)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fotoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addComponent(btnAsignarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(38, 86, 186));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Carga De Datos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(742, 742, 742)
                .addComponent(jLabel1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void obtenerDni(String cuil){
        String dni=cuil.substring(3, 11);
        txtDni.setText(dni);
    }
    void desactivar(){
        
        btnDeshacerPlanes.setEnabled(false);
        btnDeshacerTrabajo.setEnabled(false);
        
        btnAtras.setEnabled(false);
        panelContenedor.setEnabledAt(1, false);
        panelContenedor.setEnabledAt(2, false);
        btnAsignarCurso.setEnabled(false);
    }
    
    void editable(){
        //PANEL INSCRIPCION
        
        cbTipo.setEnabled(false);
        txtDni.setEditable(false);
        txtCuil.setEditable(false);
        txtNombre.setEditable(false);
        txtApellido.setEditable(false);
        
        fecha.setEnabled(false);
        cbNacimiento.setEnabled(false);;
        cbNacionalidad.setEnabled(false);;
        
        //PANEL DOMICILIO
        
        cbLocalidad.setEnabled(false);
        cbBarrio.setEnabled(false);
        cbCalle.setEnabled(false);
        txtCasa.setEditable(false);
        txtBloque.setEditable(false);
        txtPiso.setEditable(false);
        txtDepto.setEditable(false);
        txtCelular.setEditable(false);
        txtFijo.setEditable(false);
        txtCorreo.setEditable(false);
        
        //PANEL OTROS DATOS
        
        txtHijos.setEditable(false);
        cbPlan.setEnabled(false);;
        cbTrabajo.setEnabled(false);;
        //listPlan.removeAll();
        //listTrabajo.removeAll();
        
    }
    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        switch(panelContenedor.getSelectedIndex()){
            case 0:
                
                if(cbTipo.getSelectedIndex()==0 || txtDni.getText().equals("") || txtCuil.getText().equals("") || txtNombre.getText().equals("")
                    || txtApellido.getText().equals("") || cbNacimiento.getSelectedIndex()==0 || cbNacionalidad.getSelectedIndex()==0){
            
                    JOptionPane.showMessageDialog(null, "Faltan datos qué ingresar");
                }else{
                    panelContenedor.setEnabledAt(1, true);
                    panelContenedor.setSelectedIndex(1);
                    panelContenedor.setEnabledAt(0, false);
                    
                    btnAtras.setEnabled(true);
                }
                
            break;
            
            case 1:
                if(contadorGuardar==0){
                    if (cbLocalidad.getSelectedIndex() == 0 || cbBarrio.getSelectedIndex() == 0 || cbCalle.getSelectedIndex() == 0 || txtCasa.getText() == null || txtCasa.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Le falta completar domicilio: ingresar n° de casa o seleccionar localidad, barrio y/o calle.");
                        
                    } else {

                        if(txtCelular.getText().equals("")||txtFijo.getText().equals("")||txtCorreo.getText().equals("")){
                         
                            if (JOptionPane.showConfirmDialog(null, "Hay campos vacíos, ¿Quiere segeuir sin agregarlos?", "", +JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

                                panelContenedor.setEnabledAt(2, true);
                                panelContenedor.setSelectedIndex(2);
                                panelContenedor.setEnabledAt(1, false);

                            }
                        }else{
                            panelContenedor.setEnabledAt(2, true);
                            panelContenedor.setSelectedIndex(2);
                            panelContenedor.setEnabledAt(1, false);

                        }
                    }  
                    
                }else{//CUANDO YA SE HA DADO DE ALTA UNA PERSONA Y SOLO ESTÉ 'NAVEGANDO' POR LAS INTERFACES
                    panelContenedor.setEnabledAt(2, true);
                    panelContenedor.setSelectedIndex(2);
                    panelContenedor.setEnabledAt(1, false);
                }
                
            break;
            
            case 2:
                if(contadorGuardar==0){
                    btnSiguiente.setText("Terminar");
                    guardar();
                    
                }else{
                    btnSiguiente.setEnabled(false);
                }
            break;
            
                
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cbPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPlanActionPerformed

    private void cbLocalidadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbLocalidadItemStateChanged

        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(cbLocalidad.getSelectedIndex()!=0){
                Lugar item;
                item=(Lugar)cbLocalidad.getSelectedItem();           
                DefaultComboBoxModel modelo=new DefaultComboBoxModel(lugar.cargarFiltrado(item.getIdLugar(), 2));
            
                cbBarrio.setModel(modelo);
                
                CtrlCodigoPostal cod=new CtrlCodigoPostal();
                
                txtCodigo.setText(String.valueOf(cod.leer(item.getIdLugar())));
            }
        }
        
    }//GEN-LAST:event_cbLocalidadItemStateChanged

    private void cbBarrioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbBarrioItemStateChanged

        if(evt.getStateChange()== ItemEvent.SELECTED){
            if(cbBarrio.getSelectedIndex()!=0){
                Lugar item=new Lugar();
                item=(Lugar)cbBarrio.getSelectedItem();
                DefaultComboBoxModel modelo=new DefaultComboBoxModel(lugar.cargarFiltrado(item.getIdLugar(),1));
            
                cbCalle.setModel(modelo);
                
            }
        }
    }//GEN-LAST:event_cbBarrioItemStateChanged

    void guardar(){
        boolean planEmpleado=false;
        
        CtrlDomicilio domicilioId=new CtrlDomicilio();
        CtrlEdificio edificio=new CtrlEdificio();
        CtrlPersona personaCrear=new CtrlPersona();
        CtrlPlanPersona plan=new CtrlPlanPersona();
        CtrlPersonaTrabajo trabajoPersona=new CtrlPersonaTrabajo();
        CtrlAlumno alumno=new CtrlAlumno();
        CtrlFoto ctrlFoto = new CtrlFoto();
        
        TipoDocumento documento=(TipoDocumento) cbTipo.getSelectedItem();
        Lugar nacimiento=(Lugar) cbNacimiento.getSelectedItem();
        Nacionalidad nacionalidad=(Nacionalidad) cbNacionalidad.getSelectedItem();
        Lugar calle=(Lugar)cbCalle.getSelectedItem();
        byte[] imagen = fotoPanel.getBytes();
    
        int hijos=0;
        
        if(modeloPlan.isEmpty() || modeloTrabajo.isEmpty()){
            if(JOptionPane.showConfirmDialog(null, "No ha seleccionado planes y/o trabajos, ¿Quiere seguir sin agregarlos?","", + 
             JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                planEmpleado=true;
            }else{
                return;
            }   
        }
        
        //SE VERIFICA SI SE INGRESÓ ALGO CORRESPONDIENTE DE EDIFICIO..
        if (!txtBloque.getText().equals("") && !txtPiso.getText().equals("") && !txtDepto.getText().equals("")) {
            edificio.crear(txtBloque.getText(), txtPiso.getText(), txtDepto.getText());
            idEdificio = edificio.leer().getIdEdificio();
        }
        //<SE CREA UN DOMICILIO...            
        domicilioId.crear(Integer.parseInt(txtCasa.getText()), txtFijo.getText(), calle.getIdLugar(), idEdificio);

        //<SE CREA REGISTRO DE FOTO Y TRAE EL ULTIMO id
        Foto foto = new Foto();

        ctrlFoto.crear(imagen);
        foto = (Foto) ctrlFoto.leerUltimaFoto();

        //<AQUI SE DA DE ALTA UNA PERSONA..       
        if (txtHijos.getText().equals("")) {
            hijos = 0;
        } else {
            hijos = Integer.parseInt(txtHijos.getText());
        }
        Sexo item = (Sexo) cbSexo.getSelectedItem();
        personaCrear.crear(txtNombre.getText(), txtApellido.getText(), fecha.getDate(), item.getIdSexo(), txtCuil.getText(), hijos, txtCorreo.getText(), txtCelular.getText(), domicilioId.leer().getIdDomicilio(), documento.getIdTipoDocumento(), nacionalidad.getIdNacionalidad(), foto.getIdFoto(), nacimiento.getIdLugar(), false);

        personaDatos = personaCrear.leer(txtCuil.getText());

        //LOS ListModel SON PARA PODER SACAR EL TAMAÑO DE LAS LISTAS, PODER RECORRERLAS Y PODER ACCEDER AL ID DE CADA OBJETO GUARDADO
        if (planEmpleado) {

            ListModel<Planes> listaPlanes = listPlan.getModel();
            ListModel<Trabajo> listaTrabajo = listTrabajo.getModel();

            for (int i = 0; i < listaPlanes.getSize(); i++) {
                plan.crear(personaCrear.leer().getIdPersona(), listaPlanes.getElementAt(i).getIdPlanes());
            }
            for (int i = 0; i < listaTrabajo.getSize(); i++) {
                trabajoPersona.crear(personaCrear.leer().getIdPersona(), listaTrabajo.getElementAt(i).getIdTrabajo());
            }
        }

        if (personaDatos.getIdPersona() != 0) {
            JOptionPane.showMessageDialog(null, "Los datos se guardaron");

            //<SE CREA UN REGISTRO EN LA TABLA ALUMNO..
            alumno.crear(personaDatos.getIdPersona());
    
            btnSiguiente.setText("Siguiente");
            btnCancelar.setText("Salir");
            contadorGuardar++;
            btnAsignarCurso.setEnabled(true);
            panelContenedor.setSelectedIndex(0);
            panelContenedor.setEnabledAt(2, false);
            btnAtras.setEnabled(false);
            editable();
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo guardar los datos");
        }
    }    
    private void btnAsignarPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarPlanActionPerformed
        // TODO add your handling code here:
        
        if(cbPlan.getSelectedIndex()!=0){
            
            modeloPlan.addElement((Planes) cbPlan.getSelectedItem());
            cbPlan.removeItem(cbPlan.getSelectedItem());
            cbPlan.setSelectedIndex(0);
            
            btnDeshacerPlanes.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(null, "Necesita seleccionar un plan");
        }
        
    }//GEN-LAST:event_btnAsignarPlanActionPerformed

    private void btnAsignarTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarTrabajoActionPerformed
        // TODO add your handling code here:
        
        if(cbTrabajo.getSelectedIndex()!=0){
            
            modeloTrabajo.addElement((Trabajo)cbTrabajo.getSelectedItem());
            cbTrabajo.removeItem(cbTrabajo.getSelectedItem());
            cbTrabajo.setSelectedIndex(0);
            
            btnDeshacerTrabajo.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(null, "Necesita seleccionar una opción");
        }
    }//GEN-LAST:event_btnAsignarTrabajoActionPerformed

    private void btnDeshacerTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeshacerTrabajoActionPerformed
        // TODO add your handling code here:
        if(listTrabajo.getSelectedIndex()!= -1){
            cbTrabajo.addItem(listTrabajo.getSelectedValue());
            modeloTrabajo.remove(listTrabajo.getSelectedIndex());
        }
        
        if(modeloTrabajo.isEmpty()){
            btnDeshacerTrabajo.setEnabled(false);
        }
    }//GEN-LAST:event_btnDeshacerTrabajoActionPerformed

    private void btnDeshacerPlanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeshacerPlanesActionPerformed
        // TODO add your handling code here:
        if(listPlan.getSelectedIndex()!= -1){
            cbPlan.addItem(listPlan.getSelectedValue());
            modeloPlan.remove(listPlan.getSelectedIndex());
        }
        
        if(modeloPlan.isEmpty()){
            btnDeshacerPlanes.setEnabled(false);
        }
    }//GEN-LAST:event_btnDeshacerPlanesActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        
        switch(panelContenedor.getSelectedIndex()){
            
            case 1:
                panelContenedor.setEnabledAt(0, true);
                panelContenedor.setSelectedIndex(0);
                panelContenedor.setEnabledAt(1, false);
                
                btnAtras.setEnabled(false);
            break;
                
            case 2:
                panelContenedor.setEnabledAt(1, true);
                panelContenedor.setSelectedIndex(1);
                panelContenedor.setEnabledAt(2, false);
            break;
        }
        
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnAsignarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarCursoActionPerformed
        // TODO add your handling code here:
        bandera=1;
        
        AsignarCurso asignar=new AsignarCurso(personaDatos);
        
        Principal.principal.add(asignar);
        this.setComponentZOrder(asignar, 0);
        this.isOptimizedDrawingEnabled();//esto permite que si se pasa el foco a la anterior interfaz, sus componentes, no se sobre ponga al superior
        asignar.setVisible(true);
    }//GEN-LAST:event_btnAsignarCursoActionPerformed

    private void btnAgregarSxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSxActionPerformed
        // TODO add your handling code here:
        try {
    //ESTA BANDERA ES PARA SABER SI, EN CASO DE CANCELAR, SE DEBA ACTIVAR LOS PANELES DEL MENU PRINCIPAL O NO..        
            Sexo_crear.sxBandera=1;
            
            Sexo_crear sxC = new Sexo_crear();
            Principal.principal.add(sxC);
            this.setComponentZOrder(sxC, 0);
            sxC.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Inscripcion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnAgregarSxActionPerformed

    private void cbTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTipoItemStateChanged
        // TODO add your handling code here:
        txtNombre.requestFocus();
    }//GEN-LAST:event_cbTipoItemStateChanged

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtApellido.requestFocus();            
        }

    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            fecha.getFocusListeners();
        }

    }//GEN-LAST:event_txtApellidoKeyPressed

    private void txtBloqueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBloqueKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtPiso.requestFocus();
        }
    }//GEN-LAST:event_txtBloqueKeyPressed

    private void txtPisoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPisoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtDepto.requestFocus();
        }
    }//GEN-LAST:event_txtPisoKeyPressed

    private void txtCelularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtFijo.requestFocus();
        }
    }//GEN-LAST:event_txtCelularKeyPressed

    private void txtFijoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFijoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtCorreo.requestFocus();
        }
    }//GEN-LAST:event_txtFijoKeyPressed

    private void btnLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalidadActionPerformed
        // TODO add your handling code here:
        banderaInscripcionLugar=1;
        try {
            Localidad_crear crear = new Localidad_crear();
            Principal.principal.add(crear);
            this.setComponentZOrder(crear, 0);
            crear.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Inscripcion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnLocalidadActionPerformed

    private void btnBarrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarrioActionPerformed
        // TODO add your handling code here:
        banderaInscripcionLugar=1;
        try {
            Barrio_crear crear=new Barrio_crear();
            Principal.principal.add(crear);
            this.setComponentZOrder(crear, 0);
            crear.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Inscripcion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBarrioActionPerformed

    private void btnCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalleActionPerformed
        // TODO add your handling code here:
        banderaInscripcionLugar=1;
        try {
            Calles_crear crear=new Calles_crear();
            Principal.principal.add(crear);
            this.setComponentZOrder(crear, 0);
            crear.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Inscripcion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCalleActionPerformed

    private void btnActualizarTipoDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarTipoDocActionPerformed
        cbTipo.removeAllItems();
        tipo.cargarComboTipoDocumento(cbTipo);
    }//GEN-LAST:event_btnActualizarTipoDocActionPerformed

    private void btnActualizarSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarSexoActionPerformed
        cbSexo.removeAllItems();
        sx.cargarCombo(cbSexo);
    }//GEN-LAST:event_btnActualizarSexoActionPerformed

    private void btnActualizarNacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarNacionalidadActionPerformed
        cbNacionalidad.removeAllItems();
        nacion.cargarComboNacionalidad(cbNacionalidad);
    }//GEN-LAST:event_btnActualizarNacionalidadActionPerformed

    private void btnActualizarLugarNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarLugarNacActionPerformed
        cbNacimiento.removeAllItems();
        lugar.cargarComboLocalidad(cbNacimiento);
    }//GEN-LAST:event_btnActualizarLugarNacActionPerformed

    private void btnActualizarLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarLocalidadActionPerformed
        cbLocalidad.removeAllItems();
        lugar.cargarComboLocalidad(cbLocalidad);
        txtCodigo.setText("");
        cbBarrio.removeAllItems();
        cbCalle.removeAllItems();
    }//GEN-LAST:event_btnActualizarLocalidadActionPerformed

    private void btnActualizarBarrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarBarrioActionPerformed
        cbBarrio.removeAllItems();
        if(cbLocalidad.getSelectedIndex()!=0){
                Lugar item;
                item=(Lugar)cbLocalidad.getSelectedItem();           
                DefaultComboBoxModel modelo=new DefaultComboBoxModel(lugar.cargarFiltrado(item.getIdLugar(), 2));
            
                cbBarrio.setModel(modelo);
                
                CtrlCodigoPostal cod=new CtrlCodigoPostal();
                
                txtCodigo.setText(String.valueOf(cod.leer(item.getIdLugar())));
            }
    }//GEN-LAST:event_btnActualizarBarrioActionPerformed

    private void btnActualizarCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarCalleActionPerformed
        cbCalle.removeAllItems();
        if(cbBarrio.getSelectedIndex()!=0){
                Lugar item=new Lugar();
                item=(Lugar)cbBarrio.getSelectedItem();
                DefaultComboBoxModel modelo=new DefaultComboBoxModel(lugar.cargarFiltrado(item.getIdLugar(),1));
            
                cbCalle.setModel(modelo);
                
            }
    }//GEN-LAST:event_btnActualizarCalleActionPerformed

    private void btnActualizarPlanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPlanesActionPerformed
        cbPlan.removeAllItems();
        planes.cargarComboPlan(cbPlan);
    }//GEN-LAST:event_btnActualizarPlanesActionPerformed

    private void btnActualizarTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarTrabajoActionPerformed
        cbTrabajo.removeAllItems();
        trabajo.cargarComboTrabajo(cbTrabajo);
    }//GEN-LAST:event_btnActualizarTrabajoActionPerformed

    @Override
    public boolean isOptimizedDrawingEnabled(){
        return false;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarBarrio;
    private javax.swing.JButton btnActualizarCalle;
    private javax.swing.JButton btnActualizarLocalidad;
    private javax.swing.JButton btnActualizarLugarNac;
    private javax.swing.JButton btnActualizarNacionalidad;
    private javax.swing.JButton btnActualizarPlanes;
    private javax.swing.JButton btnActualizarSexo;
    private javax.swing.JButton btnActualizarTipoDoc;
    private javax.swing.JButton btnActualizarTrabajo;
    private javax.swing.JButton btnAgregarSx;
    private javax.swing.JButton btnAsignarCurso;
    private javax.swing.JButton btnAsignarPlan;
    private javax.swing.JButton btnAsignarTrabajo;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBarrio;
    private javax.swing.JButton btnCalle;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDeshacerPlanes;
    private javax.swing.JButton btnDeshacerTrabajo;
    private javax.swing.JButton btnLocalidad;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox<String> cbBarrio;
    private javax.swing.JComboBox<String> cbCalle;
    private javax.swing.JComboBox<Lugar> cbLocalidad;
    private javax.swing.JComboBox<Lugar> cbNacimiento;
    private javax.swing.JComboBox<Nacionalidad> cbNacionalidad;
    private javax.swing.JComboBox<Planes> cbPlan;
    private javax.swing.JComboBox<Sexo> cbSexo;
    private javax.swing.JComboBox<TipoDocumento> cbTipo;
    private javax.swing.JComboBox<Trabajo> cbTrabajo;
    private com.toedter.calendar.JDateChooser fecha;
    private JPanelWebCam.JPanelWebCam fotoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<Planes> listPlan;
    private javax.swing.JList<Trabajo> listTrabajo;
    private javax.swing.JPanel panel;
    private javax.swing.JTabbedPane panelContenedor;
    private javax.swing.JPanel panelInscripcion;
    private javax.swing.JPanel panelOtros;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBloque;
    private javax.swing.JTextField txtCasa;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCuil;
    private javax.swing.JTextField txtDepto;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtFijo;
    private javax.swing.JTextField txtHijos;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPiso;
    // End of variables declaration//GEN-END:variables
}
