/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazAlumno;

import Controlador.CtrlAlumno;
import Controlador.CtrlCodigoPostal;
import Controlador.CtrlCurso;
import Controlador.CtrlCursoAlumno;
import Controlador.CtrlDomicilio;
import Controlador.CtrlEdificio;
import Controlador.CtrlLugar;
import Controlador.CtrlNacionalidad;
import Controlador.CtrlPersona;
import Controlador.CtrlPersonaTrabajo;
import Controlador.CtrlPlanPersona;
import Controlador.CtrlPlanes;
import Controlador.CtrlSexo;
import Controlador.CtrlTipoCurso;
import Controlador.CtrlTipoDocumento;
import Controlador.CtrlTrabajo;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import menu.Principal;
import modelo.Edificio;
import modelo.Lugar;
import modelo.Nacionalidad;
import modelo.Persona;
import modelo.Planes;
import modelo.Sexo;
import modelo.TipoCurso;
import modelo.TipoDocumento;
import modelo.Trabajo;

/**
 *
 * @author Nero
 */
public final class Modificar extends javax.swing.JInternalFrame {
    
    Connection con = clases.Conectar.conexion();
    CtrlTipoDocumento tipo = new CtrlTipoDocumento();
    CtrlLugar lugar=new CtrlLugar();
    CtrlNacionalidad nacion= new CtrlNacionalidad();
    CtrlTrabajo trabajo=new CtrlTrabajo();
    CtrlPlanes planes=new CtrlPlanes();
    CtrlTipoCurso tipoCurso=new CtrlTipoCurso();
    CtrlSexo sx=new CtrlSexo();
    
    Persona personaDatos=new Persona();
    
    Lugar calle=new Lugar();
    Lugar barrio=new Lugar();
    Lugar localidad=new Lugar();
    Edificio edificio=new Edificio();
    ArrayList<Planes> arrayPlan = new ArrayList<>();
    ArrayList<Trabajo> arrayTrabajo = new ArrayList<>();
    ArrayList<TipoCurso> arrayCurso=new ArrayList<>();
    
    DefaultListModel<TipoCurso> modeloCurso; 
    DefaultListModel<TipoCurso> modeloDisponible;
    DefaultListModel<Planes> modeloPlanes;
    DefaultListModel<Trabajo> modeloTrabajo;
    
    int idEdificio=0;
    String detalleLocal=null;
    String detalleBarrio=null;
    String detalleCalle=null;
    
    public Modificar(Persona persona) {
       initComponents();
       
        tipo.cargarComboTipoDocumento(cbTipo);
        lugar.cargarComboLocalidad(cbLocalidad);
        lugar.cargarComboLocalidad(cbNacimiento);
        nacion.cargarComboNacionalidad(cbNacionalidad);
        trabajo.cargarComboTrabajo(cbTrabajo);
        planes.cargarComboPlan(cbPlan);
        sx.cargarCombo(cbSexo);
        
        personaDatos=persona;
        
        cargar(personaDatos);//METODO PARA EL LLENADO DE LOS DATOS TRAIDOS
        
        //TRAS HABER SIDO CARGADOS CON DATOS DE LA BD, SE LE DA ESE VALOR A LOS MODELOS RECIEN CREADOS
        //PARA PODER TANTO SACAR COMO AGREGAR ITEMS SI ES NECESARIO
        modeloPlanes= (DefaultListModel<Planes>) listPlan.getModel();
        modeloTrabajo=(DefaultListModel<Trabajo>) listTrabajo.getModel();
        
        desactivar();
        llenarArrayList();
        //filtrarComboBox();
        //comboLista();
       }
    
    void obtenerDni(String cuil){
        String dni=cuil.substring(3, 11);
        txtDni.setText(dni);
    }
    
    void desactivar(){
        btnAtras.setEnabled(false);
        panelContenedor.setEnabledAt(1, false);
        panelContenedor.setEnabledAt(2, false);
    }
    void llenarArrayList(){
        
        for(int i=0; i<modeloPlanes.getSize();i++){
            arrayPlan.add(i, modeloPlanes.getElementAt(i));
        }
        
        for(int i=0; i<modeloTrabajo.getSize();i++){
            arrayTrabajo.add(i, modeloTrabajo.getElementAt(i));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelContenedor = new javax.swing.JTabbedPane();
        panelInscripcion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtCuil = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cbNacionalidad = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cbNacimiento = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        cbSexo = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        btnAgregarSx = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        txtHijos = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cbLocalidad = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        cbBarrio = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtFijo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        cbCalle = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        txtBloque = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtPiso = new javax.swing.JTextField();
        txtDepto = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtManzana = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtLote = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtCasa = new javax.swing.JTextField();
        panelOtros = new javax.swing.JPanel();
        cbPlan = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cbTrabajo = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listPlan = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        listTrabajo = new javax.swing.JList<>();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        btnAsignarPlan = new javax.swing.JButton();
        btnAsignarTrabajo = new javax.swing.JButton();
        btnDeshacerPlanes = new javax.swing.JButton();
        btnDeshacerTrabajo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        jPanelWebCam2 = new JPanelWebCam.JPanelWebCam();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(220, 203, 203));

        panelInscripcion.setBackground(new java.awt.Color(255, 255, 255));
        panelInscripcion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Nombre");

        txtNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Apellido");

        txtApellido.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        txtCuil.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel8.setText("CUIL");

        txtDni.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel17.setText("N° de documento");

        cbTipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbTipo.setToolTipText("");
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });

        jLabel13.setText("Tipo Documento");

        cbNacionalidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbNacionalidad.setToolTipText("");

        jLabel14.setText("Nacionalidad");

        cbNacimiento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbNacimiento.setToolTipText("");
        cbNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNacimientoActionPerformed(evt);
            }
        });

        jLabel15.setText("Lugar De Nacimiento");

        jLabel5.setText("Fecha de nacimiento");

        cbSexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbSexo.setToolTipText("");

        jLabel29.setText("Sexo");

        btnAgregarSx.setBackground(new java.awt.Color(38, 86, 186));
        btnAgregarSx.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgregarSx.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarSx.setText("Agregar");
        btnAgregarSx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarSxActionPerformed(evt);
            }
        });

        jLabel25.setText("Personas a cargo");

        txtHijos.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelInscripcionLayout = new javax.swing.GroupLayout(panelInscripcion);
        panelInscripcion.setLayout(panelInscripcionLayout);
        panelInscripcionLayout.setHorizontalGroup(
            panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInscripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInscripcionLayout.createSequentialGroup()
                        .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel13)
                            .addComponent(jLabel29)
                            .addGroup(panelInscripcionLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNombre)
                                    .addGroup(panelInscripcionLayout.createSequentialGroup()
                                        .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAgregarSx)))))
                        .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelInscripcionLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelInscripcionLayout.createSequentialGroup()
                                        .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel4))
                                        .addGap(117, 117, 117)
                                        .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel8)))
                                    .addGroup(panelInscripcionLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelInscripcionLayout.createSequentialGroup()
                                                .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(panelInscripcionLayout.createSequentialGroup()
                                                        .addGap(12, 12, 12)
                                                        .addComponent(cbNacimiento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(40, 40, 40)
                                                .addComponent(fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(panelInscripcionLayout.createSequentialGroup()
                                                .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel15)
                                                    .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(txtHijos, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel25)))
                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addContainerGap())
                            .addGroup(panelInscripcionLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)
                                .addComponent(txtCuil, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81))))
                    .addGroup(panelInscripcionLayout.createSequentialGroup()
                        .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInscripcionLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(cbNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelInscripcionLayout.setVerticalGroup(
            panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInscripcionLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelInscripcionLayout.createSequentialGroup()
                        .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel17)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCuil, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(15, 15, 15)
                        .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarSx)
                    .addComponent(cbNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHijos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        panelContenedor.addTab("Inscripcion", panelInscripcion);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Localidad");

        cbLocalidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbLocalidad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLocalidadItemStateChanged(evt);
            }
        });

        jLabel16.setText("Código postal");

        txtCodigo.setEditable(false);
        txtCodigo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        cbBarrio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbBarrio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbBarrioItemStateChanged(evt);
            }
        });

        jLabel19.setText("Barrio");

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "contactos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel11.setText("Celular");

        txtCelular.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel18.setText("Telefono Fijo");

        txtFijo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel10.setText("Correo");

        txtCorreo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFijo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel21.setText("Calle");

        cbCalle.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Edificio"));

        txtBloque.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel22.setText("Bloque");

        jLabel23.setText("Piso");

        txtPiso.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        txtDepto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel32.setText("N° dto.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDepto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBloque, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBloque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txtDepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Sin nombre"));

        txtManzana.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel30.setText("Manzana");

        jLabel31.setText("Lote");

        txtLote.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel30))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(txtManzana, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel31))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtManzana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel20.setText("N° de casa");

        txtCasa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbBarrio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(cbLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(cbCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(cbBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)))
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelContenedor.addTab("Domicilio", jPanel7);

        panelOtros.setBackground(new java.awt.Color(255, 255, 255));

        cbPlan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPlanActionPerformed(evt);
            }
        });

        jLabel7.setText("Planes");

        jLabel26.setText("Trabajo");

        cbTrabajo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbTrabajo.setToolTipText("");

        listPlan.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listPlanValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listPlan);

        jScrollPane4.setViewportView(listTrabajo);

        jLabel27.setText("Planes que posee");

        jLabel28.setText("Trabajos actuales");

        btnAsignarPlan.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnAsignarPlan.setText(">");
        btnAsignarPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarPlanActionPerformed(evt);
            }
        });

        btnAsignarTrabajo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnAsignarTrabajo.setText(">");
        btnAsignarTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarTrabajoActionPerformed(evt);
            }
        });

        btnDeshacerPlanes.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnDeshacerPlanes.setText("<");
        btnDeshacerPlanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeshacerPlanesActionPerformed(evt);
            }
        });

        btnDeshacerTrabajo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnDeshacerTrabajo.setText("<");
        btnDeshacerTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeshacerTrabajoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOtrosLayout = new javax.swing.GroupLayout(panelOtros);
        panelOtros.setLayout(panelOtrosLayout);
        panelOtrosLayout.setHorizontalGroup(
            panelOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOtrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOtrosLayout.createSequentialGroup()
                        .addGroup(panelOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelOtrosLayout.createSequentialGroup()
                                .addGap(0, 64, Short.MAX_VALUE)
                                .addComponent(cbTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelOtrosLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAsignarTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(119, 119, 119)
                        .addGroup(panelOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelOtrosLayout.createSequentialGroup()
                                .addComponent(btnDeshacerTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel28))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOtrosLayout.createSequentialGroup()
                        .addGroup(panelOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelOtrosLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cbPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelOtrosLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAsignarPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(119, 119, 119)
                        .addGroup(panelOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelOtrosLayout.createSequentialGroup()
                                .addComponent(btnDeshacerPlanes, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel27)))))
                .addContainerGap())
        );
        panelOtrosLayout.setVerticalGroup(
            panelOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOtrosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel7)
                    .addComponent(btnAsignarPlan)
                    .addComponent(btnDeshacerPlanes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOtrosLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(btnDeshacerTrabajo))
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(panelOtrosLayout.createSequentialGroup()
                        .addComponent(cbPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAsignarTrabajo)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))))
        );

        panelContenedor.addTab("Otros datos", panelOtros);

        btnModificar.setBackground(new java.awt.Color(38, 86, 186));
        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar datos");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btncancelar.setBackground(new java.awt.Color(38, 86, 186));
        btncancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        btnAtras.setBackground(new java.awt.Color(38, 86, 186));
        btnAtras.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnSiguiente.setBackground(new java.awt.Color(38, 86, 186));
        btnSiguiente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelWebCam2Layout = new javax.swing.GroupLayout(jPanelWebCam2);
        jPanelWebCam2.setLayout(jPanelWebCam2Layout);
        jPanelWebCam2Layout.setHorizontalGroup(
            jPanelWebCam2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );
        jPanelWebCam2Layout.setVerticalGroup(
            jPanelWebCam2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanelWebCam2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelWebCam2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(38, 86, 186));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Modificación de datos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(742, 742, 742)
                .addComponent(jLabel1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    void cargar(Persona persona){
        CtrlLugar ctrlLugar=new CtrlLugar();
        CtrlPlanPersona ctrlPlanP=new CtrlPlanPersona();
        CtrlPersonaTrabajo ctrlTrabajoP=new CtrlPersonaTrabajo();
        CtrlAlumno ctrlAlumno=new CtrlAlumno();
        CtrlCursoAlumno ctrlCursoA=new CtrlCursoAlumno();
        CtrlEdificio ctrlEdificio=new CtrlEdificio();
        
        //PANEL INSCRIPCION
        
        //SE SELECCIONA EL TIPO DE DOCUMENTO QUE ESTÁ GUARDADO EN LA BD
        for(int i=0; i<cbTipo.getItemCount();i++){
            if(cbTipo.getItemAt(i).getDetalle().equals(persona.getIdTipoDocumento().getDetalle())){
                cbTipo.setSelectedIndex(i);
                
                i=cbTipo.getItemCount()+1;
            }
        }
        
        txtCuil.setText(persona.getCUIL());
        obtenerDni(persona.getCUIL());
        txtNombre.setText(persona.getNombrePersona());
        txtApellido.setText(persona.getApellidoPersona());
        fecha.setDate(persona.getFechaNacimiento());
        
        //ES IGUAL QUE TIPO DOCUMENTO, SOLO QUE CON LUGAR DE NACIMIENTO
        for(int i=0; i<cbNacimiento.getItemCount();i++){
            if(cbNacimiento.getItemAt(i).getNombre().equals(persona.getLugarNacimiento().getNombre())){
                cbNacimiento.setSelectedIndex(i);
                i=cbNacimiento.getItemCount()+1;
            }
        }
        
        //ESTA VEZ, CON NACIONALIDAD..
        for(int i=0; i<cbNacionalidad.getItemCount();i++){
            if(cbNacionalidad.getItemAt(i).getDetalle().equals(persona.getIdNacionalidad().getDetalle())){
                cbNacionalidad.setSelectedIndex(i);
                i=cbNacionalidad.getItemCount()+1;
            }
        }
        
        for(int i=0; i<cbSexo.getItemCount();i++){
            if(cbSexo.getItemAt(i).getIdSexo()==persona.getSexo()){
                cbSexo.setSelectedIndex(i);
                i=cbSexo.getItemCount()+1;
            }
        }
        //PANEL DOMICILIO
        
        if(persona.getIdDomicilio().getIdEdificio()!=0){
            JOptionPane.showMessageDialog(null, persona.getIdDomicilio().getIdDomicilio());
            edificio=ctrlEdificio.leer(persona.getIdDomicilio().getIdEdificio());
            
            txtBloque.setText(edificio.getTorre());
            txtPiso.setText(edificio.getPiso());
            txtDepto.setText(edificio.getDepto());
        }
        
        calle=ctrlLugar.leer(persona.getIdDomicilio().getIdLugar().getIdLugar());//obtenemos el registro de la calle guardad
        barrio=ctrlLugar.leer(calle.getDe());//usando la variable anterior, accedemos de quién depende para poder buscar el barrio
        localidad=ctrlLugar.leer(barrio.getDe());//y siendo lo mismo de arriba, usamos barrio para acceder de quién depende, es decir su localidad
        
        //ESTOS FOR SERVIRAN PARA SELECCIONAR LOS ITEMS CORRESPONDIENTES..
        //Y COMO LOS COMBOS DE BARRIO Y CALLE NO SE LLENAN DESDE UN PRINCIPIO, SE COMENZARÁ SELECCIONANDO LA LOCALIDAD PARA PODER ACCEDER AL BARRIO Y ETC
        
        for(int i=0; i<cbLocalidad.getItemCount();i++){
            if(cbLocalidad.getItemAt(i).getNombre().equals(localidad.getNombre())){//AQUI COMPARAMOS LO QUE HAYA EN EL COMBO, CON LO QUE HAYAMOS GUARDADO EN LAS VARIABLES ANTERIORES
                cbLocalidad.setSelectedIndex(i);
                detalleLocal=localidad.getNombre();
        //UNA VEZ QUE LA LOCALIDAD HAYA SIDO SELECCIONADA, QUIERE DECIR QUE EL COMBO DE BARRIO YA ESTÁ 'DISPONIBLE' POR LO TAL COMENZAMOS A PREGUNTAR IGUAL QUE HICIMOS EN LOCALIDAD    
                for(int j=0;j<cbBarrio.getItemCount();j++){
                    if(cbBarrio.getItemAt(j).getNombre().equals(barrio.getNombre())){
                        cbBarrio.setSelectedIndex(j);
                        detalleBarrio=barrio.getNombre();
                        for(int k=0; k<cbCalle.getItemCount();k++){
                            if(cbCalle.getItemAt(k).getNombre().equals(calle.getNombre())){
                                cbCalle.setSelectedIndex(k);
                                detalleCalle=calle.getNombre();
                        //UNA VEZ SELECCIONADO TANTO LOCALIDAD, BARRIO COMO CALLE, SE DARÁ A LOS INDICES UN VALOR MAYOR AL SOPORTADO PARA QUE SALGAN DE LOS FOR AUN SI FALTAN ITEMS QUÉ RECORRER         
                                k=cbCalle.getItemCount()+1;
                                j=cbBarrio.getItemCount()+1;
                                i=cbLocalidad.getItemCount()+1;
                            }
                        }
                    }
                }
            }
        }
        
        txtCasa.setText(String.valueOf(persona.getIdDomicilio().getNro()));
        txtCelular.setText(persona.getCelular());
        txtCorreo.setText(persona.getCorreo());
        txtFijo.setText(persona.getIdDomicilio().getTelefono());
        
        //PANEL OTROS DATOS
        
        txtHijos.setText(String.valueOf(persona.getHijoPersona()));
        
        //SE MANDA POR PARAMETRO A OTRO METODO PARA LLENAR LA LISTA DE PLANES CORRESPONDINETES..
        ctrlPlanP.llenarLista(persona.getIdPersona(), listPlan);
        ctrlTrabajoP.llenarLista(persona.getIdPersona(), listTrabajo);
        
    }
    
    
    
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        CtrlDomicilio domicilioId=new CtrlDomicilio();
        CtrlEdificio edificioId=new CtrlEdificio();
        CtrlPersona personaModificar=new CtrlPersona();
        CtrlPersonaTrabajo trabajoPersona=new CtrlPersonaTrabajo();
        CtrlCursoAlumno cursoAlumno=new CtrlCursoAlumno();
        CtrlAlumno alumno=new CtrlAlumno();
        CtrlCurso cursoId=new CtrlCurso();
        
        TipoDocumento documento=(TipoDocumento) cbTipo.getSelectedItem();
        Lugar nacimiento=(Lugar) cbNacimiento.getSelectedItem();
        Nacionalidad nacionalidad=(Nacionalidad) cbNacionalidad.getSelectedItem();
        Lugar calleId=(Lugar)cbCalle.getSelectedItem();
    
    //EDIFICIO
        if(!txtBloque.getText().equals("") && !txtPiso.getText().equals("") && !txtDepto.getText().equals("")){
            if(!edificio.getTorre().equals(txtBloque.getText()) || !edificio.getPiso().equals(txtPiso.getText()) || !edificio.getDepto().equals(txtDepto.getText())){                
                edificioId.editar(txtBloque.getText(), txtPiso.getText(), txtDepto.getText(), personaDatos.getIdDomicilio().getIdEdificio());
                idEdificio=personaDatos.getIdDomicilio().getIdEdificio();
            }
        }
             
    //DOMICILIO    
        if(personaDatos.getIdDomicilio().getNro()!=Integer.parseInt(txtCasa.getText()) || !personaDatos.getIdDomicilio().getTelefono().equals(txtFijo.getText())
                || calle.getIdLugar()!=calleId.getIdLugar()){
            
            domicilioId.cambiarDomicilio(personaDatos.getIdDomicilio().getIdDomicilio(), Integer.parseInt(txtCasa.getText()), txtFijo.getText(), calleId.getIdLugar(), idEdificio);        
        }
    
    //PERSONA
        if(!personaDatos.getNombrePersona().equals(txtNombre.getText()) || !personaDatos.getApellidoPersona().equals(txtApellido.getText()) || !personaDatos.getFechaNacimiento().equals(fecha.getDate())
                || !personaDatos.getCUIL().equals(txtCuil.getText()) || personaDatos.getHijoPersona()!= Integer.parseInt(txtHijos.getText()) || !personaDatos.getCorreo().equals(txtCorreo.getText())
                || !personaDatos.getCelular().equals(txtCelular.getText()) || personaDatos.getIdTipoDocumento().getIdTipoDocumento()!=documento.getIdTipoDocumento()
                || personaDatos.getIdNacionalidad().getIdNacionalidad()!=nacionalidad.getIdNacionalidad() || personaDatos.getLugarNacimiento().getIdLugar()!=nacimiento.getIdLugar()){    
            
            personaModificar.editar(personaDatos.getIdPersona(), txtNombre.getText(), txtApellido.getText(), fecha.getDate(), false, txtCuil.getText(), txtHijos.getText(), txtCorreo.getText(), txtCelular.getText(), personaDatos.getIdDomicilio().getIdDomicilio(), documento.getIdTipoDocumento(), nacionalidad.getIdNacionalidad(), 1, nacimiento.getIdLugar(), false);        
        }
        
        listaPlan();
        listaTrabajo();     
        
        if(JOptionPane.showConfirmDialog(null, "¿Desea seguir modificando datos de libros?","", + 
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                
            }else{
                dispose();
            }
    }//GEN-LAST:event_btnModificarActionPerformed

    void listaPlan(){
        ListModel<Planes> listaPlanes=listPlan.getModel();
        CtrlPlanPersona plan=new CtrlPlanPersona();
        
        //modeloPlanes POSEE LOS VALORES 'POR DEFECTO' CON LOS QUE SE LLENÓ LA INTERFAZ APENAS AL ABRIR LA INTERFAZ, Y listaPlanes ES LA ACTUAL LISTA 
        //LUEGO DE LA POSIBLE MODIFICACION.. ENTONCES, EN CASO DE QUE EL MODELO SEA MAYOR (TENGA MÁS ITEMS QUE LA OTRA LISTA) QUIERE DECIR QUE SE ELIMINARON ITEMS
        if(arrayPlan.size()>listaPlanes.getSize()){
            
        //Y PARA RECORRER AMBAS LISTAS, SE UTILIZARÁ EL MENOR PARA LUEGO, LO QUE SOBRE SE DECIDA SI SE DEBEN ELIMINAR O AGREGAR..    
            for(int i=0;i<listaPlanes.getSize();i++){
          //SI AMBOS ITEMS NO COINCIDEN RECIEN SE LLAMARÁ EL METODO PARA EDITAR EL REGISTRO.. EN CASO DE QUE COINCIDA, NO SE HARÁ NADA                             
                if(arrayPlan.get(i).getIdPlanes()!=listaPlanes.getElementAt(i).getIdPlanes()){
                    int idPlanPersona=plan.leer(personaDatos.getIdPersona(), arrayPlan.get(i).getIdPlanes()).getIdPlanPersona();                        
                    plan.editar(idPlanPersona, personaDatos.getIdPersona(), listaPlanes.getElementAt(i).getIdPlanes());
                }
            }
        
        //UNA VEZ QUE SE HAYA RECORRIDO LAS LISTAS, TENIENDO COMO LIMITE LA MENOR DE LAS LISTAS, ESTE OTRO FOR SE HARÁ CARGO, EN ESTE CASO DE 
        // 'ELIMINAR' LOS REGISTROS QUE YA NO SON NECESARIOS...
            for(int i=listaPlanes.getSize(); i<arrayPlan.size(); i++){
                int idPlanPersona=plan.leer(personaDatos.getIdPersona(), arrayPlan.get(i).getIdPlanes()).getIdPlanPersona();
                plan.borrar(idPlanPersona, arrayPlan.get(i).getIdPlanes(), personaDatos.getIdPersona());                
            }
            
        //SI listaPlanes ES MAYOR SIGNIFICA QUE SE AGREGARON MÁS ITEMS DEL QUE EN UN PRINCIO HARÍAN.. SE HARÁ LO MISMO QUE ARRIBA SOLO QUE CON EL RESTO
        //SE CREARAN NUEVOS REGISTROS EN VEZ DE 'ELIMINARLOS'..
        }else if(arrayPlan.size()<listaPlanes.getSize()){
            for(int i=0;i<arrayPlan.size();i++){
                if(arrayPlan.get(i).getIdPlanes()!=listaPlanes.getElementAt(i).getIdPlanes()){
                    int idPlanPersona=plan.leer(personaDatos.getIdPersona(), arrayPlan.get(i).getIdPlanes()).getIdPlanPersona();   
                    plan.editar(idPlanPersona, personaDatos.getIdPersona(), listaPlanes.getElementAt(i).getIdPlanes());
                }
            }
            
            for(int i=arrayPlan.size(); i<listaPlanes.getSize();i++){
                plan.crear(personaDatos.getIdPersona(), listaPlanes.getElementAt(i).getIdPlanes());
            }
            
        }else{
        //EN CASO DE QUE EL TAMAÑO DE AMBAS LISTAS COINCIDAN, LO UNICO QUE SE HARÁ ES COMPARAR CADA ITEM PARA VERIFICAR QUE SON IGUALES
            for(int i=0;i<arrayPlan.size();i++){
                    JOptionPane.showMessageDialog(null, "aqui");
                if(arrayPlan.get(i).getIdPlanes()!=listaPlanes.getElementAt(i).getIdPlanes()){
                    int idPlanPersona=plan.leer(personaDatos.getIdPersona(), arrayPlan.get(i).getIdPlanes()).getIdPlanPersona();  
                    plan.editar(idPlanPersona, personaDatos.getIdPersona(), listaPlanes.getElementAt(i).getIdPlanes());                        
                }
            }
        }
       
    }
    
    
    void listaTrabajo(){
        ListModel<Trabajo> listaTrabajo=listTrabajo.getModel();
        CtrlPersonaTrabajo ctrlTrabajo=new CtrlPersonaTrabajo();
    
        //modeloPlanes POSEE LOS VALORES 'POR DEFECTO' CON LOS QUE SE LLENÓ LA INTERFAZ APENAS AL ABRIR LA INTERFAZ, Y listaPlanes ES LA ACTUAL LISTA 
        //LUEGO DE LA POSIBLE MODIFICACION.. ENTONCES, EN CASO DE QUE EL MODELO SEA MAYOR (TENGA MÁS ITEMS QUE LA OTRA LISTA) QUIERE DECIR QUE SE ELIMINARON ITEMS
        if(arrayTrabajo.size()>listaTrabajo.getSize()){
            
        //Y PARA RECORRER AMBAS LISTAS, SE UTILIZARÁ EL MENOR PARA LUEGO, LO QUE SOBRE SE DECIDA SI SE DEBEN ELIMINAR O AGREGAR..    
            for(int i=0;i<listaTrabajo.getSize();i++){
            //SI AMBOS ITEMS NO COINCIDEN RECIEN SE LLAMARÁ EL METODO PARA EDITAR EL REGISTRO.. EN CASO DE QUE COINCIDA, NO SE HARÁ NADA
                if(arrayTrabajo.get(i).getIdTrabajo()!=listaTrabajo.getElementAt(i).getIdTrabajo()){
                    int idPersonaTrabajo=ctrlTrabajo.leer(personaDatos.getIdPersona(), arrayTrabajo.get(i).getIdTrabajo()).getIdPersonaTrabajo();                        
                    ctrlTrabajo.editar(idPersonaTrabajo, personaDatos.getIdPersona(), listaTrabajo.getElementAt(i).getIdTrabajo());
                }
            }
        
        //UNA VEZ QUE SE HAYA RECORRIDO LAS LISTAS, TENIENDO COMO LIMITE LA MENOR DE LAS LISTAS, ESTE OTRO FOR SE HARÁ CARGO, EN ESTE CASO DE 
        // 'ELIMINAR' LOS REGISTROS QUE YA NO SON NECESARIOS...
            for(int i=listaTrabajo.getSize(); i<arrayTrabajo.size(); i++){
                int idPersonaTrabajo=ctrlTrabajo.leer(personaDatos.getIdPersona(), arrayTrabajo.get(i).getIdTrabajo()).getIdPersonaTrabajo();
                ctrlTrabajo.borrar(idPersonaTrabajo, arrayTrabajo.get(i).getIdTrabajo(), personaDatos.getIdPersona());                
            }
            
        //SI listaPlanes ES MAYOR SIGNIFICA QUE SE AGREGARON MÁS ITEMS DEL QUE EN UN PRINCIO HARÍAN.. SE HARÁ LO MISMO QUE ARRIBA SOLO QUE CON EL RESTO
        //SE CREARAN NUEVOS REGISTROS EN VEZ DE 'ELIMINARLOS'..
        }else if(arrayTrabajo.size()<listaTrabajo.getSize()){           
            for(int i=0;i<arrayTrabajo.size();i++){
                if(arrayTrabajo.get(i).getIdTrabajo()!=listaTrabajo.getElementAt(i).getIdTrabajo()){                       
                    int idPersonaTrabajo=ctrlTrabajo.leer(personaDatos.getIdPersona(), arrayTrabajo.get(i).getIdTrabajo()).getIdPersonaTrabajo();            
                    ctrlTrabajo.editar(idPersonaTrabajo, personaDatos.getIdPersona(), listaTrabajo.getElementAt(i).getIdTrabajo());
                }
            }
            
            for(int i=arrayTrabajo.size(); i<listaTrabajo.getSize();i++){
                ctrlTrabajo.crear(personaDatos.getIdPersona(), listaTrabajo.getElementAt(i).getIdTrabajo());
            }
            
        }else{
        //EN CASO DE QUE EL TAMAÑO DE AMBAS LISTAS COINCIDAN, LO UNICO QUE SE HARÁ ES COMPARAR CADA ITEM PARA VERIFICAR QUE SON IGUALES
            for(int i=0;i<arrayTrabajo.size();i++){
                if(arrayTrabajo.get(i).getIdTrabajo()!=listaTrabajo.getElementAt(i).getIdTrabajo()){                        
                    int idPersonaTrabajo=ctrlTrabajo.leer(personaDatos.getIdPersona(), arrayTrabajo.get(i).getIdTrabajo()).getIdPersonaTrabajo();                        
                    ctrlTrabajo.editar(idPersonaTrabajo, personaDatos.getIdPersona(), listaTrabajo.getElementAt(i).getIdTrabajo());                        
                }
            }
        }
        
    }
    
    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        Principal.activarPanel();
        dispose();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnDeshacerTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeshacerTrabajoActionPerformed
        // TODO add your handling code here:
        if(listTrabajo.getSelectedIndex()!= -1){
            cbTrabajo.addItem(listTrabajo.getSelectedValue());
            modeloTrabajo.remove(listTrabajo.getSelectedIndex());
        }

        if(modeloTrabajo.isEmpty()){
            btnDeshacerTrabajo.setEnabled(false);
        }
    }//GEN-LAST:event_btnDeshacerTrabajoActionPerformed

    private void btnDeshacerPlanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeshacerPlanesActionPerformed
        // TODO add your handling code here:
        if(listPlan.getSelectedIndex()!= -1){
            cbPlan.addItem(listPlan.getSelectedValue());
            modeloPlanes.remove(listPlan.getSelectedIndex());
        }

        if(modeloPlanes.isEmpty()){
            btnDeshacerPlanes.setEnabled(false);
        }
        //        filtrarComboBox();
    }//GEN-LAST:event_btnDeshacerPlanesActionPerformed

    private void btnAsignarTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarTrabajoActionPerformed
        // TODO add your handling code here:

        if(cbTrabajo.getSelectedIndex()!=0){

            modeloTrabajo.addElement((Trabajo)cbTrabajo.getSelectedItem());
            cbTrabajo.removeItem(cbTrabajo.getSelectedItem());
            cbTrabajo.setSelectedIndex(0);

            btnDeshacerTrabajo.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(null, "Necesita seleccionar una opción");
        }
    }//GEN-LAST:event_btnAsignarTrabajoActionPerformed

    private void btnAsignarPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarPlanActionPerformed
        // TODO add your handling code here:
        if(cbPlan.getSelectedIndex()!=0){

            modeloPlanes.addElement((Planes) cbPlan.getSelectedItem());
            cbPlan.removeItem(cbPlan.getSelectedItem());
            cbPlan.setSelectedIndex(0);

            btnDeshacerPlanes.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(null, "Necesita seleccionar un plan");
        }
    }//GEN-LAST:event_btnAsignarPlanActionPerformed

    private void cbPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPlanActionPerformed

    private void cbBarrioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbBarrioItemStateChanged

        if(evt.getStateChange()== ItemEvent.SELECTED){
            if(cbBarrio.getSelectedIndex()!=0){
                Lugar item=new Lugar();
                item=(Lugar)cbBarrio.getSelectedItem();
                DefaultComboBoxModel modelo=new DefaultComboBoxModel(lugar.cargarFiltrado(item.getIdLugar(),1));

                cbCalle.setModel(modelo);

            }
        }
    }//GEN-LAST:event_cbBarrioItemStateChanged

    private void cbLocalidadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbLocalidadItemStateChanged

        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(cbLocalidad.getSelectedIndex()!=0){
                Lugar item;
                item=(Lugar)cbLocalidad.getSelectedItem();
                DefaultComboBoxModel modelo=new DefaultComboBoxModel(lugar.cargarFiltrado(item.getIdLugar(), 2));

                cbBarrio.setModel(modelo);

                CtrlCodigoPostal cod=new CtrlCodigoPostal();

                txtCodigo.setText(String.valueOf(cod.leer(item.getIdLugar())));
            }
        }
    }//GEN-LAST:event_cbLocalidadItemStateChanged

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:

        switch(panelContenedor.getSelectedIndex()){

            case 1:
            panelContenedor.setEnabledAt(0, true);
            panelContenedor.setSelectedIndex(0);
            panelContenedor.setEnabledAt(1, false);
            
            btnAtras.setEnabled(false);
            break;

            case 2:
            panelContenedor.setEnabledAt(1, true);
            panelContenedor.setSelectedIndex(1);
            panelContenedor.setEnabledAt(2, false);
            
            btnSiguiente.setEnabled(true);
            break;
        }

    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        switch(panelContenedor.getSelectedIndex()){
            
            case 0:
                panelContenedor.setEnabledAt(1, true);
                panelContenedor.setSelectedIndex(1);
                panelContenedor.setEnabledAt(0, false);
                
                btnAtras.setEnabled(true);
            break;
            
            case 1:
                panelContenedor.setEnabledAt(2, true);
                panelContenedor.setSelectedIndex(2);
                panelContenedor.setEnabledAt(1, false);
                
                btnSiguiente.setEnabled(false);
            break;
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void listPlanValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listPlanValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listPlanValueChanged

    private void btnAgregarSxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarSxActionPerformed

    private void cbNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNacimientoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarSx;
    private javax.swing.JButton btnAsignarPlan;
    private javax.swing.JButton btnAsignarTrabajo;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnDeshacerPlanes;
    private javax.swing.JButton btnDeshacerTrabajo;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btncancelar;
    private javax.swing.JComboBox<Lugar> cbBarrio;
    private javax.swing.JComboBox<Lugar> cbCalle;
    private javax.swing.JComboBox<Lugar> cbLocalidad;
    private javax.swing.JComboBox<Lugar> cbNacimiento;
    private javax.swing.JComboBox<Nacionalidad> cbNacionalidad;
    private javax.swing.JComboBox<Planes> cbPlan;
    private javax.swing.JComboBox<Sexo> cbSexo;
    private javax.swing.JComboBox<TipoDocumento> cbTipo;
    private javax.swing.JComboBox<Trabajo> cbTrabajo;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private JPanelWebCam.JPanelWebCam jPanelWebCam2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<Planes> listPlan;
    private javax.swing.JList<Trabajo> listTrabajo;
    private javax.swing.JPanel panel;
    private javax.swing.JTabbedPane panelContenedor;
    private javax.swing.JPanel panelInscripcion;
    private javax.swing.JPanel panelOtros;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBloque;
    private javax.swing.JTextField txtCasa;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCuil;
    private javax.swing.JTextField txtDepto;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtFijo;
    private javax.swing.JTextField txtHijos;
    private javax.swing.JTextField txtLote;
    private javax.swing.JTextField txtManzana;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPiso;
    // End of variables declaration//GEN-END:variables
}
