/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package licencia;

import Controlador.CtrlEmpleado;
import Controlador.CtrlEmpleadoLicencia;
import Controlador.CtrlLicencia;
import Controlador.CtrlPersona;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import menu.Principal;
import modelo.Empleado;
import modelo.Licencia;
import modelo.Persona;

/**
 *
 * @author RociojulietaVazquez
 */
public class AsignarLicencia extends javax.swing.JInternalFrame {
    Connection con = clases.Conectar.conexion();
    public int bandera=0;
    /**
     * Creates new form asignarLicencia
     */
    public AsignarLicencia() {
        initComponents();
        bandera=1;
        cargarCombo(cbxLicencia);
        cargarComboEmpleado(cbxEmpleado);
        bandera=0;
        txtCursos.setVisible(false);
        cursos.setVisible(false);
    }

    public void cargarCombo(JComboBox combo){
        try {
            Statement set = con.createStatement();
            ResultSet rs = set.executeQuery("SELECT articulo FROM licencia ORDER BY articulo ASC");
            combo.addItem("Seleccione uno de los articulos...");
            
            while (rs.next()) {                
                combo.addItem(String.valueOf(rs.getInt("articulo")));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
        }
    }
    
    public void cargarComboEmpleado(JComboBox combo){
        try {
            Statement set = con.createStatement();
            ResultSet rs = set.executeQuery("SELECT empleado.idEmpleado, persona.idPersona,"
                    + "persona.nombrePersona, persona.apellidoPersona FROM empleado INNER JOIN "
                    + "persona WHERE empleado.idPersona = persona.idPersona");
            
            combo.addItem("Seleccione un empleado");
            
            while (rs.next()) {
                Empleado empleado = new Empleado();
                Persona persona = new Persona();
                empleado.setIdEmpleado(rs.getInt("idEmpleado"));
                persona.setIdPersona(rs.getInt("idPersona"));
                persona.setApellidoPersona(rs.getString("nombrePersona"));
                persona.setNombrePersona(rs.getString("nombrePersona"));
                JOptionPane.showMessageDialog(null, "hola?");
                combo.addItem(persona);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbxEmpleado = new javax.swing.JComboBox<>();
        cursos = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCursos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fechaInicio = new com.toedter.calendar.JDateChooser();
        fechaFinalizacion = new com.toedter.calendar.JDateChooser();
        btnAceptar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaDetalle = new javax.swing.JTextArea();
        cbxLicencia = new javax.swing.JComboBox<>();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel2.setText("Articulo:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 118, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel3.setText("INICIO:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 249, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel4.setText("FIN:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 297, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel5.setText("Profesor:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 118, -1, -1));

        cbxEmpleado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxEmpleadoItemStateChanged(evt);
            }
        });
        jPanel2.add(cbxEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 116, 211, -1));

        cursos.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        cursos.setText("Curso/s:");
        jPanel2.add(cursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 168, -1, -1));

        jPanel1.setBackground(new java.awt.Color(38, 86, 186));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ASIGNAR LICENCIA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 726, -1));

        txtCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCursosActionPerformed(evt);
            }
        });
        jPanel2.add(txtCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 166, 211, -1));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel7.setText("Detalle:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 168, -1, -1));
        jPanel2.add(fechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 244, -1, -1));
        jPanel2.add(fechaFinalizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 292, -1, -1));

        btnAceptar.setBackground(new java.awt.Color(38, 86, 186));
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        btnAceptar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAceptarKeyPressed(evt);
            }
        });
        jPanel2.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 292, 100, -1));

        jButton2.setBackground(new java.awt.Color(38, 86, 186));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 292, 100, -1));

        areaDetalle.setColumns(20);
        areaDetalle.setRows(5);
        jScrollPane1.setViewportView(areaDetalle);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 166, 224, 79));

        cbxLicencia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxLicenciaItemStateChanged(evt);
            }
        });
        jPanel2.add(cbxLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 116, 99, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCursosActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        Date fechaInicio1 = new Date();
        Date fechaFinalizacion1 = new Date();
        Persona persona = new Persona();
        Empleado empleado = new Empleado();
        CtrlEmpleado ctrlEmpleado = new CtrlEmpleado();
        CtrlEmpleadoLicencia ctrlEmpleadoLicencia = new CtrlEmpleadoLicencia();
        Licencia licencia = new Licencia();
        CtrlLicencia ctrlLicencia = new CtrlLicencia();
        
        persona = (Persona) cbxEmpleado.getSelectedItem();
        empleado = ctrlEmpleado.leer(persona.getIdPersona());
        String articulo = (String) cbxLicencia.getSelectedItem();
        licencia = (Licencia) ctrlLicencia.leer(Integer.parseInt(articulo));
        
        if (cbxLicencia.getSelectedIndex()==0 || cbxEmpleado.getSelectedIndex()==0 ||
                fechaInicio.getDate().toString().equalsIgnoreCase("") || 
                fechaFinalizacion.getDate().toString().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Haga la carga correspondiente para poder guardar registros");
        }else{
            
            fechaInicio1 = fechaInicio.getDate();
            fechaFinalizacion1 = fechaFinalizacion.getDate();
            long i = fechaInicio1.getTime();
            long f = fechaFinalizacion1.getTime();
            java.sql.Date fecha1 = new java.sql.Date(i);
            java.sql.Date fecha2 = new java.sql.Date(f);

            
            ctrlEmpleadoLicencia.crear(fecha1, fecha2, empleado.getIdEmpleado(), licencia.getIdLicencia());
        }
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Principal.activarPanel();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbxLicenciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxLicenciaItemStateChanged
        
         CtrlLicencia ctrlLicencia = new CtrlLicencia();
        Licencia licencia = new Licencia();
        
        if (bandera==0) {
            if (cbxLicencia.getSelectedIndex()==0) {
                areaDetalle.setText("");
            }else{
                
        String articulo = (String) cbxLicencia.getSelectedItem();
        
        licencia = ctrlLicencia.leer(Integer.parseInt(articulo));
        areaDetalle.setText(licencia.getDetalle());
            }
        }
        
    }//GEN-LAST:event_cbxLicenciaItemStateChanged

    private void cbxEmpleadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxEmpleadoItemStateChanged
        /*
        
        if (bandera==0) {
            if (cbxEmpleado.getSelectedIndex()==0) {
                cbxLicencia.setSelectedIndex(0);
                areaDetalle.setText("");
                txtCursos.setText("");
                fechaInicio.setDate(null);
                fechaFinalizacion.setDate(null);
            }else{
                Persona persona =new Persona();
                CtrlEmpleado ctrlEmpleado = new CtrlEmpleado();
                Empleado empleado = new Empleado();
                
                persona = (Persona) cbxEmpleado.getSelectedItem();
                
                empleado = ctrlEmpleado.leer(persona.getIdPersona());
                
                //Contar cuantas veces se repite el idEmpleado en cursoEmpleado
                //Hacer un for con eso e ir guardando (Concatenando) los cursos para mostrarlos en el cuadro de texto
                
            }
        }
        */
        
    }//GEN-LAST:event_cbxEmpleadoItemStateChanged

    private void btnAceptarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAceptarKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            ActionEvent e = null;
            this.btnAceptarActionPerformed(e);
        }
    }//GEN-LAST:event_btnAceptarKeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            ActionEvent e = null;
            this.jButton2ActionPerformed(e);
        }
    }//GEN-LAST:event_jButton2KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaDetalle;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JComboBox<Persona> cbxEmpleado;
    private javax.swing.JComboBox<String> cbxLicencia;
    private javax.swing.JLabel cursos;
    private com.toedter.calendar.JDateChooser fechaFinalizacion;
    private com.toedter.calendar.JDateChooser fechaInicio;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCursos;
    // End of variables declaration//GEN-END:variables
}
